### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mclaudiopt** [windkh/node-red-contrib-shelly#1]
hello can you please help me to deploy this module?
thanks

**Comment by windkh** [comment]
it is still under construction...

**Comment by Dylantje** [comment]
Dear..
Is the moduel working?
I load this in Node red, only i cannot go any futher then login 
And i do not have a login selected..

**Comment by windkh** [comment]
??? Ofcouse it is working. What node red version do you use?

**Comment by Dylantje** [comment]
Thanks for je react..
I try to use shelly directly in to domoticz 
Mctt shelly to Mqtt server Domoticz..[ node red on the same domoticz server ]
[url=https://ibb.co/CQpTfFZ][img]https://i.ibb.co/CQpTfFZ/Screen-Shot419.png[/img][/url]

Only i do not get the problem..

**Comment by windkh** [comment]
So what is your problem???

**Comment by Dylantje** [comment]
i cannot connect to the shelly...
There is whatever i do always the text:  auth: false

**Comment by windkh** [comment]
Well auth:false means that authentication is turned off. Green status means ok.

**Comment by Dylantje** [comment]
ok... Thanks i do not use mqtt.. i will give it a try

Do you have perhaps a working flow?
So i can test to switch with mqqt?
I like to try to use the mqtt from shelle, without flas with tasmota or something

Only hard to get mqtt..

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-shelly/tree/master/shelly/example

The package contains an Example flow....
