### ISSUE TITLE
Reset Energy of 1PM

### ISSUE THREAD

**Issue by HubertusH** [windkh/node-red-contrib-shelly#106]
Hi,
is it somehow possible to set the energy entry to 0? In various forums one writes that the counter goes to 0 after a reboot - is there no other possibility?

![image](https://user-images.githubusercontent.com/16612146/208089511-eceb241c-2a37-4592-aa2f-23106801fca2.png)

br
Hubertus

**Comment by windkh** [comment]
I will find out ...

**Comment by windkh** [comment]
@HubertusH I could not find a way to reset the value via the API, sorry.
