### ISSUE TITLE
Controlling blinds with Shelly plus 2pm without shelly cloud

### ISSUE THREAD

**Issue by goodmike70** [windkh/node-red-contrib-shelly#107]
Hello,
We experience a problem when trying to control blinds with the Shelly plus 2PM.
Is there an example on how to use node red to control blinds in roller/cover mode without usage of the shelly cloud?
Thanks in advance!

**Comment by windkh** [comment]
@goodmike70 Hi, I do not own a shelly plus 2pm. However I tried to make an example for you:
https://github.com/windkh/node-red-contrib-shelly/blob/master/examples/rollerplus.json

Can you please check this flow if it works with your device? I made it "blindfolded", sorry in advance if it does not work.
I keep my fingers crossed.

**Comment by goodmike70** [comment]
@windkh Thanks a lot!
On the first sight it seems to work! Amazing! We will test it in detail in the next days.
Many thanks again and merry Christmas to you!

**Comment by windkh** [comment]
Ok nice ...
