### ISSUE TITLE
Shelly TRV node

### ISSUE THREAD

**Issue by stefanoc78** [windkh/node-red-contrib-shelly#108]
Great job, thanks!
I would like to report a problem with the Shelly TRV, I configured the node starting from your example, unfortunately it doesn't seem to work and the debug returns the following error message:

**"Cannot read properties of undefined (reading 'replace')"**

**Comment by windkh** [comment]
Hm what node version do you use?

**Comment by stefanoc78** [comment]
Node-RED
Current version: 14.0.1 installed in Home Assistant....

using the same "Shelly Node (Generation 1)" I tried to command a different device (shelly 1) and it works perfectly, the problem seems to be related only to the TRVs

**Comment by windkh** [comment]
I can try to find another way to implement replace so thatit works with the old node version...

**Comment by windkh** [comment]
@stefanoc78 
when do you get the error? Right after redeploy or when you triggered some action?

**Comment by windkh** [comment]
@stefanoc78 do you have access to the node-red output? I would like to see the callstack of your error message

**Comment by stefanoc78** [comment]
Sorry i gave you the home assistant plugin version 14.0.1   the Node Red version is 3.0.2

I suppose in both cases:

After redeploy (in red error color ):
4/1/2023, 18:05:05[node: 46da28b11bef0677]
msg : error
"TypeError: Cannot read properties of undefined (reading 'trim')"

when triggered (in yellow error color):
4/1/2023, 18:05:09[node: b917dfb7a5b5534e]
msg : string[55]
"Cannot read properties of undefined (reading 'replace')"

**Comment by windkh** [comment]
And what nodejs version?

**Comment by windkh** [comment]
And what version of the nodes do you use? 10.12?

**Comment by stefanoc78** [comment]
4 Jan 22:03:32 - [info] Node-RED version: v3.0.2

**4 Jan 22:03:32 - [info] Node.js  version: v18.12.1    **

**Comment by windkh** [comment]
Sorry for delay ... do you still have the same problem?

**Comment by stefanoc78** [comment]
Yes, I do. I've been trying once again but I still have the problem. 
Thanks for help

**Comment by windkh** [comment]
Can you show me your problem maybe in a teams meeting?

**Comment by windkh** [comment]
What fw version do you have? Mine is
20220811-152343/v2.1.8@5afc928c

**Comment by heximcz** [comment]
Same issue here "Cannot read properties of undefined (reading 'replace')"

Versions:
mosquitto 2.0.15
node-red 3.0.2
node 18.14.0
shelly trv 20220811-152343/v2.1.8@5afc928c

Platform:
Raspberry Pi 3B

Any of command from example https://raw.githubusercontent.com/windkh/node-red-contrib-shelly/master//examples/trv.json end with same error.

In the case of manual configuration of the "shelly gen 1" node, I also get the same error.

I have no problem connecting via teams.

**Comment by windkh** [comment]
Hm then I will have to replace the replace-function with an alternative

**Comment by windkh** [comment]
@heximcz please try 10.12.1 and if that does not work we will set up a teams meeting to find out what is going on. ok?

**Comment by heximcz** [comment]
Nice!  The bug with (reading 'replace') is apparently resolved. But now I am getting these errors:

On direct timestamp: "Error: Unauthorized /status"
On function "Temp = 30": "Error: Unauthorized /thermostat/0?target_t=25"
...

I prepared a working simple example with a standard MQTT node.
`[
    {
        "id": "5e12c48de84478f5",
        "type": "group",
        "z": "19a11a9eea571447",
        "name": "Example Shelly TRV local MQTT",
        "style": {
            "label": true
        },
        "nodes": [
            "54d6d3ed55e75698",
            "432720ba5a92caa3",
            "dad8c4df4cf53de5",
            "6b9e9a692098ee81"
        ],
        "x": 794,
        "y": 679,
        "w": 532,
        "h": 122
    },
    {
        "id": "54d6d3ed55e75698",
        "type": "mqtt out",
        "z": "19a11a9eea571447",
        "g": "5e12c48de84478f5",
        "name": "",
        "topic": "",
        "qos": "0",
        "retain": "false",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "6b9240c784c115ef",
        "x": 1250,
        "y": 740,
        "wires": []
    },
    {
        "id": "432720ba5a92caa3",
        "type": "inject",
        "z": "19a11a9eea571447",
        "g": "5e12c48de84478f5",
        "name": "23 °C",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "23",
        "payloadType": "num",
        "x": 890,
        "y": 720,
        "wires": [
            [
                "6b9e9a692098ee81"
            ]
        ]
    },
    {
        "id": "dad8c4df4cf53de5",
        "type": "inject",
        "z": "19a11a9eea571447",
        "g": "5e12c48de84478f5",
        "name": "21.5 °C",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "21.5",
        "payloadType": "num",
        "x": 890,
        "y": 760,
        "wires": [
            [
                "6b9e9a692098ee81"
            ]
        ]
    },
    {
        "id": "6b9e9a692098ee81",
        "type": "function",
        "z": "19a11a9eea571447",
        "g": "5e12c48de84478f5",
        "name": "topic target_t",
        "func": "// see https://shelly-api-docs.shelly.cloud/gen1/#shelly-trv-thermostats-0\n\n// glogal all valves\n//msg.topic = \"shellies/thermostat/0/command/target_t\";\n\n// one specific valve - FIX <ID>\nmsg.topic = \"shellies/shellytrv-<ID>/thermostat/0/command/target_t\";\n\nreturn msg;\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1090,
        "y": 740,
        "wires": [
            [
                "54d6d3ed55e75698"
            ]
        ],
        "info": "Shelly TRV supports a set of commands published\non **shellies/thermostat/0/command/** to address all TRVs\nor **shellies/shellytrv-<id>/thermostat/0/command/**\nto address an individual device:\n\n**settings**\n- will trigger publishing the content of http /settings endpoint\n\n**schedule**\n- accepts 1 or 0 to enable/disable schedule\n\n**schedule_profile**\n- accepts number from 1 to 5 to choose active schedule profile with the provided id\n\n**target_t**\n- accepts number from 4 to 31 set target temperature.\n\n**ext_t**\n- accepts number to send external sensor temperature, in deg C\n\n**valve_pos**\n- accepts number from 0 to 100 to set manually the valve position, in %\n\n**boost_minutes**\n- accepts number to start boost mode for the given minutes, in minutes\n\n**set_boost_minutes**\n- accepts number to set the default boost time, in minutes\n\n**valve_min_percent**\n- accepts number from 0 to 10 to set the valve clse postion percent, in %\n\n**accelerated_heating**\n- accepts 1 or 0 to enable/disable accelerated heating\n"
    },
    {
        "id": "6b9240c784c115ef",
        "type": "mqtt-broker",
        "name": "My Local MQTT",
        "broker": "192.168.33.1",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    }
]
`

**Comment by windkh** [comment]
Did you set a password on your shelly?

**Comment by heximcz** [comment]
@windkh yes

**Comment by heximcz** [comment]
@windkh yup! When I remove the login with password it works.

**Comment by windkh** [comment]
If you set a password then you should configure the node, too.
Enter the credentials in the node and try again please

**Comment by heximcz** [comment]
Of course I had that configured. Tried again and error: "Error: Unauthorized /status"

**Comment by heximcz** [comment]
Interestingly, logging in with RGBW2 works. That's why I didn't even think of trying TRV without a login.

**Comment by heximcz** [comment]
If it helps you, here are the headers for logging in via browser

Header from RGBW2:

`HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Shelly"
Connection: close
Content-Type: text/plain`

and from TRV:

`HTTP/1.0 401 Unauthorized
WWW-Authenticate: Basic realm="Access to site"
Server: lwIP/2.1.2 (http://savannah.nongnu.org/projects/lwip)
Content-Type: text/html`

**Comment by windkh** [comment]
@heximcz  hm that is interesting. Maybe there are different versions of the TRV in the market.
What FW version do you have installed?
Can you send me the output when you enter http://ip-of-trv-here/shelly with the correct ip ofcourse
And the same for /status please.

Do you have node red installed on your pc, too? It would be helpful in case we do a teams meeting. Then we can attach the debugger an set a breakpoint in the code.

**Comment by windkh** [comment]
@heximcz sorry I just saw that your trv has the same fw as mine…

**Comment by windkh** [comment]
@heximcz and another question. Does your username and password contain any special characters like € % & @ or blanks?

**Comment by heximcz** [comment]
> @heximcz hm that is interesting. Maybe there are different versions of the TRV in the market. What FW version do you have installed? Can you send me the output when you enter http://ip-of-trv-here/shelly with the correct ip ofcourse And the same for /status please.
> 
> Do you have node red installed on your pc, too? It would be helpful in case we do a teams meeting. Then we can attach the debugger an set a breakpoint in the code.

/shelly :
`{"type":"SHTRV-01","mac":"<mac>","auth":true,"fw":"20220811-152343/v2.1.8@5afc928c","longid":1,"discoverable":false}`

/status:
`{"wifi_sta":{"connected":true,"ssid":"<ssid>","ip":"<ip>","rssi":-56},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":true},"time":"14:16","unixtime":1676812618,"serial":132,"has_update":false,"mac":"<mac>","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"thermostats":[{"pos":1.7,"target_t":{"enabled":true,"value":19.5,"value_op":8.0,"units":"C"},"tmp":{"value":22.1,"units":"C","is_valid":true},"schedule":true,"schedule_profile":3,"boost_minutes":0,"window_open":false}],"calibrated":true,"bat":{"value":100,"voltage":4.163},"charger":false,"update":{"status":"unknown","has_update":false,"new_version":"20220811-152343/v2.1.8@5afc928c","old_version":"20220811-152343/v2.1.8@5afc928c","beta_version":null},"ram_total":97280,"ram_free":22208,"fs_size":65536,"fs_free":59372,"uptime":128833,"fw_info":{"device":"shellytrv-<id>","fw":"20220811-152343/v2.1.8@5afc928c"},"ps_mode":0,"dbg_flags":0}`

**Comment by heximcz** [comment]
> @heximcz and another question. Does your username and password contain any special characters like € % & @ or blanks?

no, just admin/admin for this test

**Comment by heximcz** [comment]
> Do you have node red installed on your pc, too? It would be helpful in case we do a teams meeting. Then we can attach the debugger an set a breakpoint in the code.

no, I don't have one, but I can test it just fine wherever it runs.

**Comment by windkh** [comment]
@heximcz can you attach a debugger ... testing alone does not help

**Comment by windkh** [comment]
@heximcz  please check out 10.13.0 and report if it works now.
I tried to reproduce it with my TRVs that I have here. If it works now then the TRV only requests case sensitive header properties: authorization must be Authorization.

**Comment by heximcz** [comment]
@windkh Nice! Its work now.

I tried to install this extension on my pc and I got a few warnings.
(I'm just adding here for thought. Otherwise, thank you, great work!)

```#npm install node-red-contrib-shelly

npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

added 46 packages, and audited 338 packages in 6s

42 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 low, 1 moderate)
```

```npm audit fix

up to date, audited 338 packages in 1s

42 packages are looking for funding
  run `npm fund` for details

# npm audit report

moment-timezone  0.1.0 - 0.5.34
Severity: moderate
Command Injection in moment-timezone - https://github.com/advisories/GHSA-56x4-j7p9-fcf9
Cleartext Transmission of Sensitive Information in moment-timezone - https://github.com/advisories/GHSA-v78c-4p63-2j6c
fix available via `npm audit fix --force`
Will install @node-red/util@1.2.3, which is a breaking change
node_modules/moment-timezone
  @node-red/util  1.2.4 - 3.0.2
  Depends on vulnerable versions of moment-timezone
  node_modules/@node-red/util
    @node-red/editor-api  1.2.4 - 3.0.2
    Depends on vulnerable versions of @node-red/util
    node_modules/@node-red/editor-api
    @node-red/registry  1.2.4 - 3.0.2
    Depends on vulnerable versions of @node-red/util
    node_modules/@node-red/registry
    @node-red/runtime  1.2.4 - 3.0.2
    Depends on vulnerable versions of @node-red/registry
    Depends on vulnerable versions of @node-red/util
    node_modules/@node-red/runtime

5 vulnerabilities (4 low, 1 moderate)
```

**Comment by windkh** [comment]
Ok nice. 
About the warnings
Well, if I update the packages for the latest nodejs versions, then a lot of people that are running on older versions of nodejs complain because it would break their systems when they upgrade the nodes.
I do not know what to do here to satisfy everybody...

**Comment by heximcz** [comment]
I get it, tough choice :-) Maybe another branch, I don't know. Thank you anyway. :+1:
