### ISSUE TITLE
wrong uptime value on gen2 devices 

### ISSUE THREAD

**Issue by Miguelguilherme** [windkh/node-red-contrib-shelly#109]
on shelly 1 pm plus, the sys.uptime value retrived from shelly cloud node is erroneous.

**Comment by windkh** [comment]
Can you provide further details?

**Comment by Miguelguilherme** [comment]
When I use the cloud node, to access shelly 1pm plus ou shelly 3 pro, the returned object have a static value on uptime. From what I see it looks like the number of restarts.I’ve tried to get the values directly from the device and the value is correct.If you need I can send an example of the payload for you to try to diagnose.I’ve tried with devices with firmware 0.12 and 0.13betaEnviado do meu iPhoneNo dia 26/01/2023, às 21:01, Karl-Heinz Wind ***@***.***> escreveu:﻿
Can you provide further details?

**Comment by windkh** [comment]
Yes please

**Comment by Miguelguilherme** [comment]
I’m out, but during the week I will send you some debug dataEnviado do meu iPhoneNo dia 27/01/2023, às 23:46, Karl-Heinz Wind ***@***.***> escreveu:﻿
Yes please

**Comment by windkh** [comment]
@Miguelguilherme 
I crosschecked with a gen 2 PM1 see image below
You can see both, the status from the cloud at the top and the status from the device underneath in blue.
Time is 
11:48 uptime 234 for response from the cloud and
12:00 uptime 964 for the response from the device directly

Uptime seems to be in seconds. The cloud data is not up to date as it is only updated from time to time.
So the cloud API does not seem to contact the device but access cached data which is stored in the cloud when getting the status. The data which is returned by the node comes directly from the shelly server. If that is a problem in your eyes then you need to contact the shelly developers... sorry I can not do anything about it.  
 
![image](https://user-images.githubusercontent.com/10910767/215321820-add4db81-f00b-4692-a5c4-e23cf2cfaa9b.png)
