### ISSUE TITLE
Connect to Shelly Cloud API

### ISSUE THREAD

**Issue by EivindTjessem** [windkh/node-red-contrib-shelly#111]
HI, I try to configure a Shelly Cloud Node. But cant find setting for Device ID.
The version is 10.13.1, and I have restarted HA.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/109388566/220598666-b3af6fce-3354-432f-bb93-ae5ef675e22f.png">

**Comment by windkh** [comment]
You can find it in your shelly app under info
![image](https://user-images.githubusercontent.com/10910767/220750495-5be7939a-04f2-4b22-b6fc-8eb1662b2260.png)

**Comment by EivindTjessem** [comment]
I find the solution, it is not an configuration in the cloud node. But it need to be sendt as an input in payload.
msg.payload = {
    type : 'status',
    id: '98cdxx246287'
};

That works


But the help function says that an empty payload will return status. (then you needed to sett the ID in  configuration)
So the help text could be updatet.

**Comment by windkh** [comment]
@EivindTjessem Ah I see... the device ID was part of the config node in earlier versions. Now it must be passed in payload. I adapted the help. Please have a look at the examples that come along with the nodes....
