### ISSUE TITLE
Shelly type mismatch: SPEM-003CEBEU

### ISSUE THREAD

**Issue by FrodoVDR** [windkh/node-red-contrib-shelly#112]
Shelly type mismatch: SPEM-003CEBEU

The new Shelly Pro 3EM are not recognised, but the output is OK.

**Comment by windkh** [comment]
Ok I will add this signature. 
Is it compatible to the EM3?

**Comment by windkh** [comment]
@FrodoVDR I assume that you configured it as gen 2 device Relay? Or?

**Comment by windkh** [comment]
@FrodoVDR I extended the nodes, but I can not test it as I do not have a 3EM Pro model here.
Can you support me with testing?

**Comment by windkh** [comment]
closed due to no response from reporter
