### ISSUE TITLE
Dimmer 2 timer value

### ISSUE THREAD

**Issue by tjarb** [windkh/node-red-contrib-shelly#113]
Hi there,

Has the shelly dimmer2 also a (auto) timer off value which can be passed with each command (instead of a global device config)?
```
    msg.payload = {
        brightness: level,
        transition: 5000, // optional 0..5000ms
        on: state,
        timer: 300     //dimmer set-action expire time
    };
```

Best regards

**Comment by tjarb** [comment]
Hi WindKH,

Thank you for your reply. I'll explain the purpose:
When the light is turned 'on' bij a central controller (dark, motion, etc), then the user is 'served'. When the controller must turn the dimmer off actively (state=false) the user will not be able to manually turn the lights on again (the controller want the lights OFF).
So, I'm looking for a way the central controller only have to send 'ON' to turn lights (dimmer) on, and if not (no action, timed out) the user is still able to manually flip the switch.

Thank you for adding this feature in next release.

Best regards

**Comment by windkh** [comment]
[V10.13.2](https://github.com/windkh/node-red-contrib-shelly/releases/tag/V10.13.2) should be available in a few minutes.
please report if it worked

**Comment by tjarb** [comment]
It worked as expected. Thanks for the quick release.

Best regards,

**Comment by windkh** [comment]
Cool thanks!!!!
