### ISSUE TITLE
shelly gen1 node type RGBW debug output when no hostname provided

### ISSUE THREAD

**Issue by novski** [windkh/node-red-contrib-shelly#117]
Seams like shelly gen1 type RGBW is the only device type that prints "Failed to get mode from settings" when Hostname is not given. All other device types give out status Hostname not configured but do not print to debug. 
Can RGBW device type be changed to behave same as the other device types?

**Comment by windkh** [comment]
I will ...

**Comment by windkh** [comment]
Now the device type will be checked before mode is retrieved
