### ISSUE TITLE
shelly gen 1, RGBW Mode change does not reset all Button switched URL's

### ISSUE THREAD

**Issue by novski** [windkh/node-red-contrib-shelly#118]
If I configure my shelly gen 1 RGBW to use callback mode and then go back to Polling mode the "Button switched OFF", "Short" and "Long" press URL's don't get erased. Only the "Button switched ON URL" get's erased.
I think that's not correct.

**Comment by windkh** [comment]
I remember that there was an issue with erasing stuff when going back to polling mode... I need to reproduce it before I can tell you more

**Comment by windkh** [comment]
I guess that is solved in the meantime
