### ISSUE TITLE
shelly gen 1, RGBW2 Button switched ON, OFF, Short and Long URL's get overwriten

### ISSUE THREAD

**Issue by novski** [windkh/node-red-contrib-shelly#119]
I had some URLs in the action's config to react to a button, switching on and off motion sensors when pressed.
After configuring NR node to callback mode, those URLs got overwritten.
I consider that wrong.

**Comment by windkh** [comment]
Hm,... never tried it. Let me try to reproduce it here

**Comment by windkh** [comment]
RGBW gen1 is outdated... won't be fixed
