### ISSUE TITLE
Error status is sticky

### ISSUE THREAD

**Issue by jflyper** [windkh/node-red-contrib-shelly#12]
Error messages appear as status text for a shelly node seems to be sticky. The messages remain even when the node is working without a problem.

One thing to note is that the name is `.local` (mDNS name). Somewhere in the name lookup process generates this error and the status display picking it up?

![Node-RED___pi_local](https://user-images.githubusercontent.com/14850998/104818326-4a399f00-586a-11eb-8547-5c10e43c1457.jpg)

**Comment by windkh** [comment]
I will fix this

**Comment by windkh** [comment]
1.7.2 should fix this
