### ISSUE TITLE
all_status not implemented?

### ISSUE THREAD

**Issue by arvidcarlandercompose** [windkh/node-red-contrib-shelly#121]
Hi,

I am new to this repo so please excuse the ramblings of a newbie.

Very glad to find a repo for the Shelly Cloud. First thing I wanted to do was to get a list of devices from Shelly Cloud. Example suggests a type: all_status. I can find the elseif for status but not for all_status.

Am I being an idiot or has the all_status not been implemented yet? If so, I would like to see if I can make my first little contribution and add it (or try to).

-Arvid

**Comment by windkh** [comment]
@arvidcarlandercompose thanks for your contribution, added you to the credits.
