### ISSUE TITLE
Shelly Gen1 Node killed my Shelly

### ISSUE THREAD

**Issue by osulivanDE** [windkh/node-red-contrib-shelly#124]
For a very long time I was wondering why my Shelly 2.5 reboots once a day, every few days or even multiple times a day. 

I watched this happen for a year and recently replaced the Node-Red Shelly Gen1 nodes with calls directly from Home Assistant. 
From the moment I deleted the Node-Red Shelly Node the daily rebooting stopped. 

I am sure that this is not a problem with the Node-Red Nodes but rather with the firmware of the Shelly 2.5. 
Maybe people have the same problem so i want to document this problem here.

The best way to see the problem is that every time the Shelly rebooted, my shelly power balance did reset. Meanwhile, the sensor has been running clean for 6 days without failure.

<img width="830" alt="Bildschirmfoto 2023-09-13 um 22 15 39" src="https://github.com/windkh/node-red-contrib-shelly/assets/44095221/c02d558b-68eb-49e8-a774-6abb5816d42c">

**Comment by windkh** [comment]
That is strange. Maybe an internal exception triggered reboot. Can you send me the flow?

**Comment by osulivanDE** [comment]
Sorry, i already deleted the flow but it was basically just this within the message object:

{
    roller : 0,
    go : 'close/open'
}

**Comment by windkh** [comment]
@osulivanDE if the node talks to the shelly depends on the mode you selected:
- Polling mode: the node calls /shelly route every few seconds
- Callback mode: the shelly calls the node but not vice versa
- None mode: no communication, only if input of node is triggered

what did you choose?

**Comment by osulivanDE** [comment]
I used Polling Mode.

**Comment by windkh** [comment]
what do you mean with "power balance did reset"

**Comment by osulivanDE** [comment]
The "Energy" reading in Home Assistant from my Shelly is a accumulative reading which resets when the Shelly reboots (intentionally or unintentionally) And as long this reading doesn´t reset my Shelly has no problems.
<img width="565" alt="Bildschirmfoto 2023-09-17 um 21 05 26" src="https://github.com/windkh/node-red-contrib-shelly/assets/44095221/5e55149f-f3c8-4fcb-8ebe-6141f820b561">

**Comment by windkh** [comment]
@osulivanDE you are talking about a shelly 2.5?
https://shelly-api-docs.shelly.cloud/gen1/#shelly2-5

**Comment by windkh** [comment]
@osulivanDE the shelly 2.5 does not really support metering like e.g. a shelly EM.
To proof the theory that it really restarts I reset my shelly 2.5 and from now on I will check the uptime under
http://<your-shelly-IP-here>/shelly

I hope that I can reproduce it here at my home and then we'll see

**Comment by osulivanDE** [comment]
It would be great to have someone reproduce this problem. I had two Nodes connected to one Shelly 2.5. Maybe even more nodes make it faster to reproduce this problem?


It is indeed a Shelly 2.5 with metering.
This is from its status page:

Shelly 2.5
Hardware: gen1 (SHSW-25)

**Comment by windkh** [comment]
I have the same ones and it says that it contains two meters. However they only show the current consumed power forveach direction. I have not found a value for total consumption...

**Comment by windkh** [comment]
Uptime is 82996s today. So still running. I keep you informed

**Comment by windkh** [comment]
Uptime is 380798s today 25.9. morning. It means it rebooted 4,4 days ago. 
FW is "20230913-112234/v1.14.0-gcb84623"

**Comment by windkh** [comment]
Uptime is 685962s today 28.9 evening 21:05. It means it rebooted 7,9 ago.

**Comment by windkh** [comment]
Uptime is 211813s today 7.10. evening 20:52. It means it rebooted 2 days ago.
Hm I am not sure but this time I guess I installed a new firmware.

**Comment by windkh** [comment]
Ok last test: I created a flow that monitors the uptime and counts the reboots.

**Comment by windkh** [comment]
Result after days of testing:
![image](https://github.com/windkh/node-red-contrib-shelly/assets/10910767/537bc52d-12fc-42b5-94cb-2ce45fec9876)

![image](https://github.com/windkh/node-red-contrib-shelly/assets/10910767/3a259500-abed-4d1a-887e-543f292bf31b)

I can not reproduce the problem

**Comment by osulivanDE** [comment]
Thank you for testing. Maybe it is a special combination of hardware in my case why this happens to me.
