### ISSUE TITLE
Gen2 device stuck on "Uploading script"

### ISSUE THREAD

**Issue by hollenal** [windkh/node-red-contrib-shelly#125]
I have a Shelly 2 Plus PM that I wanted to include in a flow using Callback mode. However, after setting up the shelly-gen2-server and deploying the change, the node keeps saying "Uploading script" and no script is actually being uploaded to the device.
No password protection, all devices in the same LAN subnet.

Any idea what I might be doing wrong?

![image](https://github.com/windkh/node-red-contrib-shelly/assets/76468852/a0c18343-ffbb-42bc-a020-5d0058e35313)

![image](https://github.com/windkh/node-red-contrib-shelly/assets/76468852/c8d93b14-a910-489c-91b6-1fd57f35d67e)

**Comment by windkh** [comment]
If this is a device that sleeps, like a shelly smoke or button, then wake it up. The node will retry this as long as the node shows up. If not then we should debug it together

**Comment by windkh** [comment]
Yes indeed,... but if you try polling mode it works, yes?

**Comment by windkh** [comment]
On what device do you run node-red? Is it possible to attach a debugger there?

**Comment by hollenal** [comment]
I’m running it on a raspi. I have other nodes that are accepting incoming connections (http in) on that same instance of node red.

Am 20.09.2023 um 22:29 schrieb Karl-Heinz Wind ***@***.***>:

﻿

On what device do you run node-red? Is it possible to attach a debugger there?

**Comment by windkh** [comment]
You could try the following:
in 99-shelly.js somewhere at line 1892: please uncomment the following lines by removing the leading //

// node.error("Uploading script failed " + error);
// node.status({ fill: "red", shape: "ring", text: "Uploading script failed "});

And then let me know if an error is printed

**Comment by hollenal** [comment]
Yes, I get the following:

![image](https://github.com/windkh/node-red-contrib-shelly/assets/76468852/ab85db64-dbcf-45c2-b37d-2d83a0168002)

**Comment by windkh** [comment]
@hollenal that is strange, should we organize a teams meeting where you can show me the problem?

**Comment by hollenal** [comment]
Yes, let's do that. I'll contact you via mail.

**Comment by windkh** [comment]
What firmware version do you use?
I am asking because further problems are reported with the latest update.

**Comment by windkh** [comment]
I close this issue as duplicate: please follow #128
