### ISSUE TITLE
Shelly Mini PM missing in type def ("SNPM-")

### ISSUE THREAD

**Issue by impact0815** [windkh/node-red-contrib-shelly#127]
The Shelly Mini PM has the prefix "SNPM-", please add it to the gen2DeviceTypes.
Thx!

**Comment by windkh** [comment]
@impact0815 as I do not own such a device type: is it compatible to the standard Shelly PM?
Maybe you can do some testing for me?

**Comment by impact0815** [comment]
Sure!
I added it already in my local instance: 
_["Measure",    ["SPEM-", "SNPM-"]]_
 and it is working as expected. 
It worked before that change, but throw the message of incompatible type.
Can you guide me what to look after/test!?

With my current config, it gets this content: 
{"status":{"ble":{},"cloud":{"connected":false},"mqtt":{"connected":true},"pm1:0":{"id":0,"voltage":232.1,"current":0.025,"apower":0,"freq":50,"aenergy":{"total":10.773,"by_minute":[0,0,0],"minute_ts":1}},"sys":{"mac":"ababababab","restart_required":false,"time":"09:41","unixtime":1,"uptime":57469,"ram_size":261536,"ram_free":100984,"fs_size":393216,"fs_free":94208,"cfg_rev":9,"kvs_rev":0,"schedule_rev":0,"webhook_rev":0,"available_updates":{}},"wifi":{"sta_ip":"10.0.0.2","status":"got ip","ssid":"abc","rssi":-68},"ws":{"connected":false}},"payload":{"pm10":{"id":0,"voltage":232.1,"current":0.025,"apower":0,"freq":50,"aenergy":{"total":10.773,"by_minute":[0,0,0],"minute_ts":1}}},"_msgid":"1"}

**Comment by impact0815** [comment]
Oh, and the correct product name is: "Shelly Plus PM Mini".
On Shellys Webpage it is categorized as "Switching and triggering", in my opinion it's measuring only, but... ;)

**Comment by impact0815** [comment]
Sadly not (yet). :(

**Comment by windkh** [comment]
> Sure! I added it already in my local instance: _["Measure", ["SPEM-", "SNPM-"]]_ and it is working as expected. It worked before that change, but throw the message of incompatible type. Can you guide me what to look after/test!?
> 
> With my current config, it gets this content: {"status":{"ble":{},"cloud":{"connected":false},"mqtt":{"connected":true},"pm1:0":{"id":0,"voltage":232.1,"current":0.025,"apower":0,"freq":50,"aenergy":{"total":10.773,"by_minute":[0,0,0],"minute_ts":1}},"sys":{"mac":"ababababab","restart_required":false,"time":"09:41","unixtime":1,"uptime":57469,"ram_size":261536,"ram_free":100984,"fs_size":393216,"fs_free":94208,"cfg_rev":9,"kvs_rev":0,"schedule_rev":0,"webhook_rev":0,"available_updates":{}},"wifi":{"sta_ip":"10.0.0.2","status":"got ip","ssid":"abc","rssi":-68},"ws":{"connected":false}},"payload":{"pm10":{"id":0,"voltage":232.1,"current":0.025,"apower":0,"freq":50,"aenergy":{"total":10.773,"by_minute":[0,0,0],"minute_ts":1}}},"_msgid":"1"}

I guess you should add it as a "Relay" device as "Measure" is rather for Shelly EM and EM3 devices.
That should basically be everything. The check is only performed to be able to discover if IP addresses change on the local network and to avoid that you suddenly talk to a different type of device.
