### ISSUE TITLE
Shelly Plus1 error when uploading script on latest firmware

### ISSUE THREAD

**Issue by andrew-brightman** [windkh/node-red-contrib-shelly#128]
After upgrading two of my Shelly Plus 1 devices to firmware 1.0.3 I am getting these errors

![image](https://github.com/windkh/node-red-contrib-shelly/assets/67860865/7df51983-4a72-4ad1-b97c-194c3ac0efc5)

![image](https://github.com/windkh/node-red-contrib-shelly/assets/67860865/bd40376a-8687-4d3b-a651-cbd1fc3bdffd)

I still have one Plus 1 on formware 0.14.1 and it is working fine.

**Comment by windkh** [comment]
Thanks for reporting. Maybe the same problem as #125. 
I will update mine and check

**Comment by windkh** [comment]
I studied the changelog 
https://shelly-api-docs.shelly.cloud/gen2/changelog/

Maybe this could be the reason:
https://shelly-api-docs.shelly.cloud/gen2/changelog/#100-2023-08-03

_Authentication in HTTP client, supporting basic and digest schemes. This enables the [HTTP](https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/HTTP) service and [webhooks](https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Webhook) to access password-protected URLs._

**Comment by andrew-brightman** [comment]
It seems as though somewhere in [this](https://github.com/windkh/node-red-contrib-shelly/blob/ad512d0ed326d6d73b0b6d7f1a7c341fd1af685b/shelly/99-shelly.js#L1831) try block is where the error is. I noticed the code in the corresponding catch block was only [uncommented ](https://github.com/windkh/node-red-contrib-shelly/commit/c286fdb91043716591eebdefb6324059573554e6) in version 10.13.8 not long ago so it may have been silently failing for quite some time?

**Comment by windkh** [comment]
If uploading fails, then a retry will be triggered. This is required for devices that are sleeping most of the time like the shelly HT or smoke detector. But for a permanently powered device upload must never fail. ECONNRESET indicates that the shelly terminated the session. If the device would sleep I would expect another error...

**Comment by windkh** [comment]
![image](https://github.com/windkh/node-red-contrib-shelly/assets/10910767/35516263-f6dc-478e-afb4-019a5e3f696b)

after upgrading from 
"fw_id": "20221206-141253/0.12.0-gafc2404",
to
 "fw_id": "20230912-081941/1.0.3-g6176478",
upload failed

--> I can reproduce it with a Shelly Plus 1PM

**Comment by windkh** [comment]
Already first request fails:
 let createParams = { 'name' : scriptName };
let createScriptResonse = await shellyRequestAsync('GET', '/rpc/Script.Create', createParams, credentials);

**Comment by windkh** [comment]
opened an issue at shelly support...waiting

**Comment by windkh** [comment]
I guess I found a part of the problem. In former fw versions parameters could be passed in the body while now they must com along as encoded url parameters...
Script can be uploaded now. Still struggling to start the scripts...

**Comment by windkh** [comment]
Ok found another "feature" in the firmware:
when creating a script in the shelly and deleting it again, it stays hidden in memory.
When recreating the script the old data is there. And when the node tries to upload the program code, then it is appended until the resources are exhausted.

**Comment by windkh** [comment]
And found another "feature" in the latest firmware:
Start should be a POST request. Now I found out that you must do a GET. The example is wrong or the code of the firmware
https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Script#scriptstart-example

**Comment by andrew-brightman** [comment]
All good again. Thanks for the quick turnaround.

![image](https://github.com/windkh/node-red-contrib-shelly/assets/67860865/095d877c-e340-4a42-9b0d-33b09acd93b6)
