### ISSUE TITLE
Shelly gen 2: check if webhook has similar problems with new firmware (HT)

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-shelly#129]
see #128

**Comment by LokiMidgard** [comment]
I had the problem, that the webhook was never installed with a Shelly PlusHT , however unlike the linked issue, it will not show any errors just hangs at installing webhook

![image](https://github.com/windkh/node-red-contrib-shelly/assets/389101/1e079a66-c0fb-40a2-ad65-2469cba228b5)

**Comment by windkh** [comment]
As long as the HT sleeps it will stay in this mode. As soon as it wakes up it installs the webhook. You can just wait or wake it up manually.

**Comment by windkh** [comment]
If it worked before and you updated the firmware, then also update the nodes

**Comment by LokiMidgard** [comment]
I just started using node-red (currently migrating away from openhab). So I can't say that it worked before the update.

I also made a factory reset so no configuration of openhab was present.

I keept the device waked up using the button. I also used two nodes (both update modes) and the pull provided values the other not. I assume I should see the webhook under Webhooks in the admin site of the device?

**Comment by windkh** [comment]
Yes correct

**Comment by windkh** [comment]
1. check if polling works
2. try without setting a password in the shelly first
3. use the latest version of the nodes an fw

**Comment by LokiMidgard** [comment]
From the log of the HTPlus it looked like it dose not get past webhook.Listsupported

![image](https://github.com/windkh/node-red-contrib-shelly/assets/389101/6710bf11-d0f7-469b-878a-5bb846207f50)


So I uncommented https://github.com/windkh/node-red-contrib-shelly/blob/4832d41604b4e02e26180171a554421e5d725420/shelly/99-shelly.js#L1986-L1987

and now I get:
```
Installing webhook failed TypeError: supportedEventsResponse.hook_types is not iterable
```

The response looks like following:
```json
{
    "types": {
        "temperature.change": {
            "attrs": [
                {
                    "name": "tC",
                    "type": "number",
                    "desc": "New temperature in Celsius"
                },
                {
                    "name": "tF",
                    "type": "number",
                    "desc": "New temperature in Farenheit"
                }
            ]
        },
        "humidity.change": {
            "attrs": [
                {
                    "name": "rh",
                    "type": "number",
                    "desc": "New humidity in %"
                }
            ]
        }
    }
}
```

**Comment by LokiMidgard** [comment]
I changed the `for of` to an `for in` loop on `types`, now it did registered the callbacks. I can see the actions in the device.

I'm not sure of other sides effects, but you can see my changes here:
https://github.com/windkh/node-red-contrib-shelly/compare/master...LokiMidgard:node-red-contrib-shelly:patch-1

**Comment by kdsohn** [comment]
I am not sure, whether it's the same pproblem or a new one. I am using the latest version of modul an fw (of 20230912) and cannot register a webhook on a shelly plus smoke, even when starting with the device beeing online.

**Comment by windkh** [comment]
@kdsohn  will check it here

**Comment by windkh** [comment]
I have checked with fw 20230420-115805/0.14.3-gd976dc3: it worked after I woke up the shelly.

Then I updated to fw 20231031-152239/1.07-g5db02bd: it failed.

I believe that the Webhook was removed in the new version: https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyPlusSmoke

**Comment by windkh** [comment]
And again shelly changed the api in an incompatible way: now the hook_types array returned from "/rpc/Webhook.ListSupported'" is not an array again but an object. In addition to that it is renamed to types.
--> next version should fix this.
