### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by agarest-lab** [windkh/node-red-contrib-shelly#13]
Hi
I have tried in various ways but I cannot control and see the status of my Shelly1 through your nodes.
I also tried to remove the cloud operation from my Shelly1 but nothing has changed.
The message is always: unauthorized
If you want, I also have a Shelly2.5 but I haven't tried it yet.

I don't have any password set for the Shelly, is it necessary to set one with its username?

**Comment by windkh** [comment]
Sorry for delay,... can you post your flow?
