### ISSUE TITLE
GEN 2 | Callback Mode | If Shelly is password protected install script fails

### ISSUE THREAD

**Issue by teixemf** [windkh/node-red-contrib-shelly#132]
If a Shelly is password protected, while activating the Callback Mode, installing the script fails while calling "_/rpc/Script.GetStatus_"
The debugger returns  the message: _"Uploading script failed Unauthorized /rpc/Script.GetStatus"_

https://github.com/windkh/node-red-contrib-shelly/blob/ad512d0ed326d6d73b0b6d7f1a7c341fd1af685b/shelly/99-shelly.js#L1880

If uninstalling the script, it also fails calling the same route "_/rpc/Script.GetStatus_"
The node lights up red with the message: Uninstalling script failed
![image](https://github.com/windkh/node-red-contrib-shelly/assets/816267/9150b7bd-0405-4ef6-8c0d-e5189fd59da6)

I believe the root cause of the issue is related to the function _shellyRequestAsync()_ and the way it deals with a GET with the credentials variable set and the _params_ variable different then _NULL_ 
I believe it because the function that gets the Scripts List calls a GET with credentials set but with the _params_ variable set to _NULL_ 

https://github.com/windkh/node-red-contrib-shelly/blob/1ddedcbe9a004881532adb49839b8fec6065007a/shelly/99-shelly.js#L1836

and doesn't return error.

Meanwhile, while uninstalling the script, the GET call to _/rpc/Script.Delete_ also returns error.

https://github.com/windkh/node-red-contrib-shelly/blob/1ddedcbe9a004881532adb49839b8fec6065007a/shelly/99-shelly.js#L1933

During the my tests I also found the POST call to _/rpc/Script.Delete_ in the uninstall script function, has the parameters _"params"_ and _"data"_ missplaced.

**Comment by windkh** [comment]
Thanks for reporting, will check it out if I am back.

About the params and data: recently the api was changed when updating from fw 0.x to 1.x
In former versions params were expected and from 1.x on POST calls required the values in the body. I already complained at the shelly support.

**Comment by teixemf** [comment]
`await shellyRequestAsync('GET', '/rpc/Script.Delete', params, null, credentials);`
returns fine if your Shelly has is not password protect.
but it returns error if you have the password set.

`await shellyRequestAsync('GET', '/rpc/Script.List', null, null, credentials);`
always returns fine whether you have a password set or not.

That's why I believe it appears to be an issue with _shellyRequestAsync()_ when using GET + params != null + shelly with password enabled. While I couldn't understand why these combination makes _shellyRequestAsync()_ I wrote a workaround for the issue using POST to call _Script.GetStatus_ nas _Script.Delete_

@windkh I can make a pull request you want.

**Comment by windkh** [comment]
The shelly support said that the developers will update the documentation... I am a bit confused what they did. 

Yes please make a pull request so that I can see what you tested so far. I will also do some tests as soon as I find some time ...
