### ISSUE TITLE
BLU Motion sensor, BLU Gateway

### ISSUE THREAD

**Issue by ahartman** [windkh/node-red-contrib-shelly#136]
Any chance of supporting the new devices in your fine package?
Regards, ahartman

**Comment by windkh** [comment]
Ok I will order one and try what I can do

**Comment by ahartman** [comment]
Dear Karl-Heinz,

Thank you, I am looking forward to it.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
Devices arrived today
The gateway should be easy to integrate 
https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyBluGw

**Comment by windkh** [comment]
Maybe a new script needs to be created for scanning Bluetooth signals and passing them forward to node-red
https://github.com/ALLTERCO/shelly-script-examples/blob/main/ble-shelly-blu.js

**Comment by windkh** [comment]
@ahartman 

in my tests the gateway is currently a node that can be used inside node-red. This node could just scan for bluetooth signals end emit the received values in raw format. if so you would need to process that raw data in node-red to find out what button or sensor triggered the message. 

As an alternative I could create an additional node for all BLU devices: next to "gen1" and "gen2" there would be a third called "blu". But as bluetooth device do not have an IP address I would need to find another way for identifying the devices e.g. the device ID which can be found in the shelly app.

What do you think would be better?

**Comment by ahartman** [comment]
Dear Karl-Heinz,

I think the first challenge is to get a Bluetooth link. I did not yet manage to link the sensor either to my Mac or to my iPhone.
I also purchased the Shelly Blu-Gateway; supposedly the sensor connects to that gateway and the gateway forwards the data from the sensor over Wifi.
I also did not yet manage to link the sensor to the gateway as I cannot find instructions how to do that.
I submitted a support request to Shelly how to do this but no answer yet.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
@ahartman please test with the new gateway node

**Comment by ahartman** [comment]
Dear Karl-Heinz,

I installed your version 10.15.0 but there is no gateway node in the node package.

I only see:

shelly gen 1
shelly gen 2
shelly cloud

Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
Take gen 2 node. Then choose the type BLU-Gateway from the list where you have Relay, Dimmer,...

**Comment by ahartman** [comment]
Karl-Heinz,

Gateway is connected and reports {empty} in a debug node.

I cannot get the BLU Sensor to link over Bluetooth to the Gateway.
I press the Sensor button 10 seconds and it starts blinking blue.

Then I press the button on the Gateway until red blinking.
When I release the button I sometimes get one short blue blink but then it turns red and green again.
No UI to see what is happening, maddening.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
Did you add the device to your Wifi with the new blue shelly app?

**Comment by ahartman** [comment]
Karl-Heinz,

No, I did via the browser interface on 192.168.33.1.
Does that make a difference in the Bluetooth linking between gateway and sensor? 
That still does not work for me.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
@ahartman 
if you can access 192.168.33.1 via browser that is good:
just re-configure the shelly: you need to add it to your wifi by name and password under the settings menue so that it receives a new IP from your home. It needs to be in the same network segment where your node-red device is: e.g. 192.168.178.x
After configuring the wifi the shelly may be rebooted.
