### ISSUE TITLE
Shelly RGBW2 support

### ISSUE THREAD

**Issue by Docjones** [windkh/node-red-contrib-shelly#14]
Hello,

are there any plans to support the shelly RGBW2 LED device any time?

regards
Marc

**Comment by windkh** [comment]
I will integrate this soon. Thanks

**Comment by windkh** [comment]
version 1.7.0 contain your changes

**Comment by Docjones** [comment]
I am a total noob in this node-stuff. Did i miss somethine? The rgbw2 part didnt seemt to 'activate'

![image](https://user-images.githubusercontent.com/561429/120145003-2a849100-c1e3-11eb-9318-cc0c5696d9f5.png)

**Comment by windkh** [comment]
I could not test your pull request so far as I am waiting for my shellyRGBW to arrive.
