### ISSUE TITLE
current and voltage data crashes script on Plus 2 PM

### ISSUE THREAD

**Issue by Solarer** [windkh/node-red-contrib-shelly#142]
The callback script crashes on my Shelly Plus 2PM because when pressing a button the device starts reporting voltage and current data at a very high rate which overloads the script when it tries to forward these events to my node red server.

```
Uncaught Error: Too many calls in progress
15:54:55 at );
15:54:55 ^
15:54:55 in function "CallNodeRed" called from CallNodeRed(event)
15:54:55 ^
15:54:55 in function called from system
15:54:55 CallNodeRed: {"component":"cover:0","name":"cover","id":0,"now":1707836094.99998998641,"info":{"component":"cover:0","id":0,"event":"current_update","current":0.6,"ts":1707836095}}
15:54:55 Uncaught Error: Too many calls in progress
15:54:55 at );
15:54:55 ^
15:54:55 in function "CallNodeRed" called from CallNodeRed(event)
15:54:55 ^
15:54:55 in function called from system
```

After filtering out `power_update` and `current_update` events, the script works as expected.

**Comment by windkh** [comment]
Hm can you send me your modifications?
Besides current_update events ... are there any further chatty events?

**Comment by Solarer** [comment]
I created a PR.
As far as I can tell, these are the only events that spammed the function call

**Comment by windkh** [comment]
merged
