### ISSUE TITLE
shelly1 node crash node-red

### ISSUE THREAD

**Issue by dieterferdinand** [windkh/node-red-contrib-shelly#143]
hello,
today i have the problem, that the shelly1 node crash my node-red.

i try to find out why and find this reason:
hostname = msg.payload.hostname;

the problem is, that msg is defined, msg.payload is defined, but msg.payload is not an object!

i try to solve the problem, but this change "if (msg.payload.hostname !== undefined)" does not help.
i don't know, at the moment, how i can test a variable is an object or not un node-red.

i don't know, what the content of msg.payload is, but i will try to be sure, that the node can't get an invalid message in the future.

goodby

**Comment by windkh** [comment]
@dieterferdinand can you provide an example?

**Comment by dieterferdinand** [comment]
hello,
not possible at the moment and if i test it, i will kill my node-red.
[flows (7).json](https://github.com/windkh/node-red-contrib-shelly/files/14576867/flows.7.json)

i use this flow to switch the relais and after i find this bug, i changed my function to check the payload and prevent such problems.

but i think, that all messages, in which informations are missing, can trigger this bug.

first i use  a switch node to create the object from a true or false payload to switch the relais, so all false messages can pass, now i check if payload is true oder false und if not, i will not send a message to the shelly node!

i don't remember, what was in the message, if node-red was crashing. it is posible the payload was a number or a string.

to make some test, i must install an other instance of node-red because the other system must running!

the shelly 1 node check this:
if(msg !== undefined && msg.payload !== undefined){
msg is defined and msg.payload is defined!
but msg.payload.hostname ist not defined and this line will crash node-red:
hostname = msg.payload.hostname; 

it is no problem, to check the message befor it is send to the node, but if node-red crash, this is a problem, but this node must be deaktivated, all flows backed up, deleted and reimported and changed or the flows-file must be edited.

goodby.

**Comment by windkh** [comment]
Thanks for reporting... will check this asaü

**Comment by windkh** [comment]
please check 10.18.0

**Comment by dieterferdinand** [comment]
hello,
i update the node and look in the code.

it is good, to use a function to validate the payload. but this function:
function isMsgPayloadValid(msg) {
        let isValid = false;
        if (msg && msg.payload && !Array.isArray(msg)) {
            if (!Array.isArray(msg.payload) && !isEmpty(msg.payload)) {
                isValid = true;
            }
        }
        return isValid;
    }
test only if msg and msg.payload exist and that it is no array. but the rest of the program needs an object in msg.payload and you don't test msg.payload for an object. if there is a value in payload and the program needs an object, it will crash!
and all programcode which use this function, needs an OBJECT in msg.payload!

you can use typeof msg.payload === "object" to check for an object, but this is no test for the existens for any value in the object like msg.payload.command!
and if nodejs access this variable and it don't exist, it crashes.

i have also update to nodejs 20 today.

i think, i will try to install nodejs on an other system, on which i can test, what crash node-js. i have to many crashes today and not for all, i know why!

goodby

**Comment by dieterferdinand** [comment]
hello,
i find this side with a script for detecting an object:
https://underscorejs.org/docs/modules/isObject.html

goodby

**Comment by dieterferdinand** [comment]
hello,
the only problem with this function, an array is also an object!

goodby

**Comment by windkh** [comment]
Arrays are ignored now

**Comment by dieterferdinand** [comment]
hello,
 i see it, but it is possible, that payload is not an object and the value object.hostname or other values does not exist which is the reason for the crash!

goodby

**Comment by windkh** [comment]
Have you tested this with the version I released yesterday?

**Comment by windkh** [comment]
Please test it and let me know

**Comment by dieterferdinand** [comment]
hello,
i have installed the actuall node-red on my server and test it. but i don't know, what the node get, if it crash. with my tests, it have not crashed the server.

goodby

**Comment by dieterferdinand** [comment]
hello,
is it possible, do get the uptime and wifi rssi level with the shelly nodes?

this information is also in the status-information with the power, relais and input-information?

the uptime is needed, to check, if the device is automatic restarted and the wifi level to check if the shelly is connect to the false wlan-ap.

goodby

**Comment by windkh** [comment]
> hello, is it possible, do get the uptime and wifi rssi level with the shelly nodes?
> 
> this information is also in the status-information with the power, relais and input-information?
> 
> the uptime is needed, to check, if the device is automatic restarted and the wifi level to check if the shelly is connect to the false wlan-ap.
> 
> goodby

yes the uptime,  rssi level of wifi is available
