### ISSUE TITLE
Cant switch my Shelly Plus 2PM

### ISSUE THREAD

**Issue by manueltuescher** [windkh/node-red-contrib-shelly#145]
Hi @all
What am I doing wrong? 

I've been trying to switch my Shelly Plus 2 PM via NodeRed for almost 2 hours, but it just won't work. 

I have done everything as described on the Shelly.Doc page, see picture:
![image](https://github.com/windkh/node-red-contrib-shelly/assets/95418143/cc7546ab-d5fe-4bb4-8d81-b0ed98eaaad4)

The Shelly doesn't switch, I don't hear the relay switching or anything on the web interface
Does anyone have any ideas what else I can do? 
Am I doing something wrong?

**Comment by windkh** [comment]
Did you try the example in the examples folder?

**Comment by manueltuescher** [comment]
i have to say, that i am an absolute beginner. how can i set this example file up?

**Comment by manueltuescher** [comment]
i found the error.. fixed

**Comment by windkh** [comment]
The examples can be imported in node-red from the sidebar. Import ... examples
