### ISSUE TITLE
Shelly EM3 / Button show "installing webhook" for "Callback" devices forever in Docker node-red with bridge network

### ISSUE THREAD

**Issue by Henry-Jones** [windkh/node-red-contrib-shelly#148]
I recently changed the docker image form "host" network to "bridge" network.

Around the same time, i updated the node-red image to 3.1.7 and the shelly Node to 10.18.0

So its rather tricky to pinpoint the reason for the change.

I forward the Ports 1880, 19091 (Button) and 19092 (EM3) to the Docker container. The webinterface seems to work without problems. I also can start the "download csv" demo from the manual succesfully.

The button might be at sleep (I'm quite away from it currently) but the EM3 is live and working. The button worked before and maybe it still does, but the EM3 does not get any actions set.

Are there other ports to open ? Or something else I can check and report ?

**Comment by windkh** [comment]
Hm I guess you should show me what is going on in a teams meeting.

**Comment by Henry-Jones** [comment]
We can arrange that, but company rules prevent sharing the control of the PC, so only watching would be possible, I can also make screenshots of the relevant things, if this helps.

**Comment by Henry-Jones** [comment]
I'm now directly connected to the network. There the problem is slightly different:
- the Shelly devices report "Online" after shortly displaying "installing webhook"
- the webhooks dont get installed
- if I install the webhook by hand, it works as expected (only tried with the button so far, the EM3 cannot be switched off currently).

Can I find a log what gets sent to the shelly devices and what they report back ? This might be easier as a teams session.

**Comment by windkh** [comment]
@Henry-Jones no there is no log... if the webhooks don't get installed, then the nodes can not communicate with the shellies in the network or?

**Comment by Henry-Jones** [comment]
That's likely the case.

Obviously the shellies dont have this problem in the other direction, when the webhook is set manually.

For testing purposes I added a ping-node [node-red-node-ping](https://flows.nodered.org/node/node-red-node-ping) This node can reach the shelly and reports back the roundtrip time successfully.

**Comment by windkh** [comment]
just do a GET http://<here your shelly ip>/shelly

**Comment by Henry-Jones** [comment]
This results in:
(EM3)
```
{
    "type": "SHEM-3",
    "mac": "485519D6CEDF",
    "auth": false,
    "fw": "20230913-114244/v1.14.0-gcb84623",
    "discoverable": true,
    "longid": 1,
    "num_outputs": 1,
    "num_meters": 0,
    "num_emeters": 3,
    "report_period": 1
}
```
(Button)
```
{
    "type": "SHBTN-2",
    "mac": "485519F04680",
    "auth": false,
    "fw": "20230913-113105/v1.14.0-gcb84623",
    "discoverable": true,
    "longid": 1,
    "sleep_mode": true
}

```
when I use the following url (according to [this](https://shelly-api-docs.shelly.cloud/gen1/#settings-actions) the webhook gets set: `http://192.168.15.180/settings/actions?index=0&name=out_on_url&enabled=true&urls[]=http://192.168.1.4/on&urls[]=http://192.168.1.5/on`

**Comment by windkh** [comment]
@Henry-Jones 
You can use one port for all callbacks as the script in the shellies send their IP Address in to node-red. So inside node red it can be checked from what shelly the call was.
