### ISSUE TITLE
Dimming via slider not working after update

### ISSUE THREAD

**Issue by ht38f** [windkh/node-red-contrib-shelly#150]
I use a slider to dim the lights up/down. After the update when I dim to 0, the value is not taken into the shelly node.
1-99% works well, but if I go from example 30% down to 0% it stays at 30%
Dimming to 0% via input directly via shelly components still works.

[flows-14.json](https://github.com/windkh/node-red-contrib-shelly/files/14807982/flows-14.json)

**Comment by windkh** [comment]
Thanks for reporting. I will fix this as soon as I am back from vacation

**Comment by ht38f** [comment]
Thank you!

**Comment by ht38f** [comment]
This error is still present with update 10.21.0

**Comment by windkh** [comment]
@ht38f I am fixing the problems you discovered. However there are also bugs in your flow which you should adapt, too.

msg.on is always undefined  --> this defaults to "on"
msg.light is always undefined --> this defaults to 0

next relase should fix your problems

**Comment by windkh** [comment]
@ht38f thanks for reporting

**Comment by ht38f** [comment]
Thank you. Now it works!
