### ISSUE TITLE
Shelly HT ERROR: connect EHOSTUNREACH after update

### ISSUE THREAD

**Issue by ht38f** [windkh/node-red-contrib-shelly#152]
[ShellyHT.json](https://github.com/windkh/node-red-contrib-shelly/files/14843104/ShellyHT.json)

![Screenshot 2024-04-01 213130](https://github.com/windkh/node-red-contrib-shelly/assets/112893474/e140fd25-f6a9-4d5b-ae25-974f40b64e0b)

Shelly HT ERROR: connect EHOSTUNREACH after update. see attached photo and flow

**Comment by ht38f** [comment]
This Shelly HT
https://www.shelly.com/en/products/shop/shelly-plus-h-and-t

**Comment by ht38f** [comment]
It is still the same issue with 10.21.0

**Comment by windkh** [comment]
@ht38f I tested your flow and it works here... can you make sure that the shelly's IP is reachable from where you run node-red?

**Comment by ht38f** [comment]
Shelly should be reachable. I did a factory reset, gave it a new static ip based on MAC address in the router. The sensor is mostly disconnected but shows up a few seconds in the router and disappears again. I assume this is to preserve battery

**Comment by windkh** [comment]
So why do you get an error if it works here? Hm strange

**Comment by windkh** [comment]
Did you press the inject node while the shelly is sleeping?

**Comment by ht38f** [comment]
I tried. Same issue. I now watched the app and waited for it to update.23.19:25 it updated the Shelly app. 
![IMG_0228](https://github.com/windkh/node-red-contrib-shelly/assets/112893474/636cf704-5e48-449e-8388-ae8eacbe0152)
![IMG_0227](https://github.com/windkh/node-red-contrib-shelly/assets/112893474/53faef80-d4ae-4547-bc1e-7f95be18c3d5)

**Comment by windkh** [comment]
@ht38f the AxiosError occurs when you inject while the shelly is sleeping. That is ok, as the node can not talk to the shelly in this state. Devices that sleep should be run in "callback" mode.
Nevertheless the connect EHOSTUNREACH is strange.
Is something logged to the node-red console?

**Comment by ht38f** [comment]
Shelly firmware is 20240223-141926/1.2.2-g7c39781

**Comment by ht38f** [comment]
I am running node red on a Victron Cerbo and have no access to the files :(

**Comment by windkh** [comment]
> Shelly firmware is 20240223-141926/1.2.2-g7c39781

0240223-141926/1.2.2-g7c39781 is installed on mine

**Comment by ht38f** [comment]
So it’s the same. I just received a debug showing data from the sensor!
![IMG_0229](https://github.com/windkh/node-red-contrib-shelly/assets/112893474/2d9101e1-1900-409d-b2da-061339361b68)

**Comment by windkh** [comment]
Did you set a password?

**Comment by ht38f** [comment]
No password

**Comment by windkh** [comment]
@ht38f what node-red version and what nodejs version do you use?

**Comment by ht38f** [comment]
3.1.5

**Comment by windkh** [comment]
do you use different IP Address ranges in your home?
what is the IP of the victron device?

**Comment by ht38f** [comment]
Think js is v18

**Comment by ht38f** [comment]
Victron is 192.168.1.138

**Comment by ht38f** [comment]
Shelly sensor is also in cloud. That’s how I see it updates.

**Comment by windkh** [comment]
what happens if you enter the following into the browser
http://192.168.1.207/rpc/Shelly.GetStatus

**Comment by ht38f** [comment]
I need to check. I am not at the install but working remotely from victron VRM. I tried to connect to 192.168.1.207 earlier today. I did not manage to connect. I believe the device turns on and connects to the router and then goes back to sleep so it is not more visible

**Comment by windkh** [comment]
will go to bed now... maybe we should do a teams meeting where you can show it to me.

**Comment by ht38f** [comment]
I have been watching the flow and suddenly it says connected and is green. A few seconds after it goes back to ehostunreach

**Comment by ht38f** [comment]
Have a good night! Thanks for the help!

**Comment by windkh** [comment]
@ht38f hi... sorry I forgot to ask if the error is still there or not?

**Comment by ht38f** [comment]
Hi. The error is still there. When I try to get the status http://192.168.1.207/rpc/Shelly.GetStatus
I get this: The server at 192.168.1.207 is taking too long to respond.

This makes sense as the H&T is only connected to the router a few seconds before it goes back to sleep.
All other Shelly devices work normal.

**Comment by windkh** [comment]
The shellies that normally sleep like HT or smoke or door/window should not be polled. Instead you should use callback mode.
