### ISSUE TITLE
Support for Shelly Plus 0-10V Dimmer

### ISSUE THREAD

**Issue by BjornHoorelbeke** [windkh/node-red-contrib-shelly#154]
Hello,

Is there any ETA on the support for Support for the 0-10V Dimmer please?

Regards,

Bjorn

**Comment by windkh** [comment]
Hi, 
I do not own such a dimmer. Would have to buy one first to be able to do some testing.

**Comment by BjornHoorelbeke** [comment]
That is the one indeed

**Comment by windkh** [comment]
Device is ordered... waiting for delivery

**Comment by windkh** [comment]
@BjornHoorelbeke please install 10.24.0 and have a look at the dimmerplus.json example
