### ISSUE TITLE
BLU Motion sensor issues

### ISSUE THREAD

**Issue by ahartman** [windkh/node-red-contrib-shelly#160]
Dear Karl-Heinz,

We communicated on this about a year ago; due to work I put the sensor aside.
I now tried again setting this up and it works; I have 2 questions:

1. I would think Node-Red 'sees' each time the sensor blinks red because of motion but that is not the case. it seems to miss many motion events. Is there a reason for that and can I do something about it?
2. I would like to receive the luminance value regularly without having to wait on a motion detection; is it possible to poll the sensor for the luminance?
3. 
Kind regards, ahartman, Belgium

**Comment by ahartman** [comment]
Karl-Heinz,

I use it in call back mode. I found out there is a blind period after sending an event, probably to save power. You can set that it the Smart Control app and it is currently on 60 seconds.
Too bad about the luminance. I could set it to beacon mode, but that the battery will not last very long, I think.
There was no point 3, my fault.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations, Freundliche Grüße,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België

**Comment by windkh** [comment]
Hi André,
You could connect a light sensor to a shelly uni or shelly add-on if you need iluminance monitoring.
Or you could power your BLU motion by cable.
