### ISSUE TITLE
Shelly plus 2PM v2!?

### ISSUE THREAD

**Issue by impact0815** [windkh/node-red-contrib-shelly#161]
For the Shelly plus 2PM there is the model number in the config
"SNSW-002P16EU" 
as correct per KB https://kb.shelly.cloud/knowledge-base/shelly-plus-2pm

But my device is returning "SNSW-**1**02P16EU" (Firmware 1.3.3) (Ver2?)

I changed the config.json to "my" number and it works again as expected.
Without the change I get
"Error: AxiosError: timeout of 5000ms exceeded"

Thanks for your support/work!

**Comment by windkh** [comment]
Hi thanks for reporting, I will add your device to the config.

**Comment by windkh** [comment]
@impact0815 I compared the number with other devices that have different versions like
https://kb.shelly.cloud/knowledge-base/shelly-pro-1pm-v1

I assume that the first number is the version 0=V0, 1=V1, 2=V2. So I guess you found V1 and the documentation refers to V0.

**Comment by windkh** [comment]
@impact0815 in the other hand here it is V2 -->  SNPL-10112EU
https://kb.shelly.cloud/knowledge-base/shelly-plus-plug-s-v2
