### ISSUE TITLE
Shelly type mismatch: SPSW-201PE16EU

### ISSUE THREAD

**Issue by imagoxmediasystems** [windkh/node-red-contrib-shelly#162]
Thank you for your great work. 
Here is a Shelly Pro 1PM with the identifier SPSW-201PE16EU that is currently not supported. 
The type is listed in the official Shelly documentation: https://kb.shelly.cloud/knowledge-base/shelly-pro-1pm-v1
It would be great if you could add the type. Thank you!

**Comment by windkh** [comment]
@imagoxmediasystems thanks for reporting. I will add it!
