### ISSUE TITLE
Shelly Dimmer 0/1-10V PM Gen3 adjust brightness with node red

### ISSUE THREAD

**Issue by EricSoft4** [windkh/node-red-contrib-shelly#165]
I tried to changes the brightness from a Shelly Dimmer 0/1-10V PM Gen3 . In the shelly gen 2+ node you can select it from the pull down. I get the information from the shelly no problem but when i send a message
msg.payload = {
    id: 0,
    on: false,
    brightness: 100
}
return msg;
it doesn't change.
Maybe I should post another message, but I can't find anything.

**Comment by windkh** [comment]
https://github.com/windkh/node-red-contrib-shelly/blob/master/examples/dimmerplus.json

**Comment by EricSoft4** [comment]
![image](https://github.com/windkh/node-red-contrib-shelly/assets/87763969/9baea89d-7f87-4dc6-92ce-3b91821b6330)
It's empthy what i see
