### ISSUE TITLE
Support for Shelly Plus RGBW PM

### ISSUE THREAD

**Issue by MrTom1** [windkh/node-red-contrib-shelly#167]
Hi,

please add support for device Shelly Plus RGBW PM.

**Comment by windkh** [comment]
hm I need to buy one first

**Comment by MrTom1** [comment]
> hm I need to buy one first

Perhaps this information can help you for implementation:

https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen2/ShellyPlusRGBWPM
