### ISSUE TITLE
Please add support for Shelly motion sensor

### ISSUE THREAD

**Issue by dfgas** [windkh/node-red-contrib-shelly#17]
Please add support for shelly motion sensor. thank you

**Comment by windkh** [comment]
I do not have any... must order one first

**Comment by mopenmind** [comment]
Maybe this helps - the msg.payload is as follows:
{"motion":true,"timestamp":1622300251,"active":true,"vibration":false,"lux":2063,"bat":97}

**Comment by windkh** [comment]
I will add this... maybe you can test it then?

**Comment by windkh** [comment]
version 1.9.0 supports it
