### ISSUE TITLE
Node Red service exist when entering wrong port number in Shelly-gen-1 node

### ISSUE THREAD

**Issue by WolfgangKnobloch** [windkh/node-red-contrib-shelly#170]
Using Shelly-gen-1 node to report data from Shelly H&T, using the callback server mode.
Made a mistake in specifying  too big a port number 100152 for the callback server ( instead of 10152).

Instead of generating an error message this brought down the whole node-red service and it won't restart afterwards, instead always fails an same point.  I had to manually edit the json file to reverse the issue. 

Versions: 
Jul 30 19:00:28 raspberrypi Node-RED[1882]: 30 Jul 19:00:28 - [info] Node-RED Version: v3.0.2
Jul 30 19:00:28 raspberrypi Node-RED[1882]: 30 Jul 19:00:28 - [info] Node.js  Version: v16.20.2
Jul 30 19:00:28 raspberrypi Node-RED[1882]: 30 Jul 19:00:28 - [info] Linux 6.1.21-v8+ arm64 LE
Jul 30 19:00:29 raspberrypi Node-RED[1882]: 30 Jul 19:00:29 - [info] Paletten-Nodes werden geladen
Jul 30 19:00:30 raspberrypi Node-RED[1882]: 30 Jul 19:00:30 - [debug] Module: node-red-contrib-shelly 10.14.3 /home/wolfgang/.node-red/prod/node_modules/node-red-contr>

Error Log from system (journalctl):

Jul 30 19:00:34 raspberrypi Node-RED[1882]: 30 Jul 19:00:34 - [red] Uncaught Exception:
Jul 30 19:00:34 raspberrypi Node-RED[1882]: 30 Jul 19:00:34 - [error] RangeError: options.port should be >= 0 and < 65536. Received 100152.
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at new NodeError (node:internal/errors:387:5)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at validatePort (node:internal/validators:365:11)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at Server.listen (node:net:1591:5)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at /home/wolfgang/.node-red/prod/node_modules/fastify/lib/server.js:156:14
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at manageErr (/home/wolfgang/.node-red/prod/node_modules/fastify/fastify.js:507:11)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at exit (/home/wolfgang/.node-red/prod/node_modules/fastify/lib/hooks.js:90:5)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at next (/home/wolfgang/.node-red/prod/node_modules/fastify/lib/hooks.js:101:9)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at hookRunnerApplication (/home/wolfgang/.node-red/prod/node_modules/fastify/lib/hooks.js:83:3)
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at /home/wolfgang/.node-red/prod/node_modules/fastify/fastify.js:496:11
Jul 30 19:00:34 raspberrypi Node-RED[1882]:     at Object._encapsulateThreeParam (/home/wolfgang/.node-red/prod/node_modules/avvio/boot.js:551:7)
Jul 30 19:00:34 raspberrypi systemd[1]: nodered-prod.service: Main process exited, code=exited, status=1/FAILURE
Jul 30 19:00:34 raspberrypi systemd[1]: nodered-prod.service: Failed with result 'exit-code'.

**Comment by windkh** [comment]
Thanks for reporting.... I will limit the port number to 16bit in future
