### ISSUE TITLE
Error econnreset

### ISSUE THREAD

**Issue by Avabehe** [windkh/node-red-contrib-shelly#172]
Hi,

Since the new version of node-red-contrib-shelly there is a problem if the checkbox  "Enable status output after each command" is activated.- ("Error Read ECONNRESET")
For me, its a big problem, I am working with the status data after sending a command, so there is always an error.
In the example files the checkbox isnt activated, so they are working ;)

Sry the post #169 is already marked as closed, its the reason why I have opened a new one ;)

BG

**Comment by windkh** [comment]
Will have a look at it after my vacation

**Comment by Avabehe** [comment]
Thank you, if you need any further informations, contact me.

If there is any relevance, I am using the Shelly Plus Plug S.

Schönen Urlaub noch 😀
