### ISSUE TITLE
Error on device type scan

### ISSUE THREAD

**Issue by hoeken** [windkh/node-red-contrib-shelly#173]
I am trying to get started with a Shelly Pro 1PM.  In node-red I add the gen2 node, fill the IP and then which I click the 'scan' icon it gives me this error:

```Device could not be found in config. Please report device type in github.```

I looked in the code and it seems like its supported.  Digging into the http responses, this is the json that is getting returned from that detect query:

```json
{
"name":null,
"id":"shellypro1pm-0cb815fde320",
"mac":"0CB815FDE320",
"slot":0,
"model":"SPSW-201PE15UL",
"gen":2,
"fw_id":"20240625-122912/1.3.3-gbdfd9b3",
"ver":"1.3.3",
"app":"Pro1PM",
"auth_en":false,
"auth_domain":null
}
```

**Comment by windkh** [comment]
Woop woop! Thanks for reporting. I will add it to the config.json. 

If you want to you can add this on your own by just making a cooy of a line in the config.json and change the data according to the data you sent above. Br kh
