### ISSUE TITLE
Shelly Pro 3

### ISSUE THREAD

**Issue by rbuurveld** [windkh/node-red-contrib-shelly#175]
Hi, would it be possible to add support for the Shelly Pro 3 (the 3-channel relais). If it helps, let me know how I can send one to you.

**Comment by windkh** [comment]
Maybe it works out of the box... have you tried to configure it using the auto detect function?

**Comment by windkh** [comment]
@rbuurveld any news? did you check it?

**Comment by rbuurveld** [comment]
It works perfectly! Turns out the Pro3 is in the list, I could just select it, it connected and works. My bad, I checked the description for the package, didn't see the Pro3 and didn't look further... :-(  Thanks for following up on this.
