### ISSUE TITLE
Callback Connection error: -14

### ISSUE THREAD

**Issue by jimwest256** [windkh/node-red-contrib-shelly#178]
Hello,

Since upgrading to the latest version of Node-Red-Contrib-Shelly and my Shelly devices, I noticed that the callback from the script no longer works.

Error in the shelly log:
`shelly_http_client.:304 0x3ffdf46c: HTTP PUT http://192.168.178.60:10001/callback
22:57:12
shelly_http_client.:607 0x3ffdf46c: Finished; bytes 0, code 0, redir 0/3, auth 0, status -1: Connection error: -14`

If I open the URL for the callback in the browser, I receive an error "Website not reachable"

Any ideas?

Thanks!

**Comment by windkh** [comment]
Hi I discovered the same problem a few hours ago. Probably the upgrade of the fastify package caused the problem. I hope that I already found the problem: will release a new version today. Thanks for reporting

**Comment by jimwest256** [comment]
Works with the new version. Thank you!
