### ISSUE TITLE
Shelly Pro 2 type mismatch: SPSW-202XE12UL

### ISSUE THREAD

**Issue by RobertsonRhyan** [windkh/node-red-contrib-shelly#179]
Hi,

Thanks for the great job.
Could you add this device type please SPSW-202XE12UL, it's a Shelly Pro 2.

Cheers

**Comment by windkh** [comment]
The id is nearly the same except for UL at the end: SPSW-202XE12UL
SPSW-202XE16EU 

What does UL stand for?

**Comment by RobertsonRhyan** [comment]
I'm not sure, I think it's just a different certification but the two look identical.

**Comment by windkh** [comment]
UL-certified means it is certified for the market in US and Canada

**Comment by RobertsonRhyan** [comment]
Strange I bought it in Switzerland. But good to know
