### ISSUE TITLE
Shelly1 loses wifi connection (not just node-red effected)

### ISSUE THREAD

**Issue by smithy-eng** [windkh/node-red-contrib-shelly#18]
Hi

Over the last few weeks I have been testing the Shelly 1. Initially my tests were using the Shelly App and the Shelly Cloud all worked as expected even notifications messages. Then I thought I try your nodes in node-red. What I have seen repeatedly is this: after 2-3 hrs the shelly device shows disconnected in node-red, a network scan reveals the Shelly has simply 'disappeared', gone offline! The only way to bring back the device online is to cycle the power.

Before using your nodes (REST API) the device would never ever disconnect, online for over 7 days straight.

Now for the interesting bit, I don't believe it's your nodes, it's the Shelly that's at fault and if you search the internet for 'Shelly Disconnected' you will find multiple threads on the subject mainly from OpenHab and Home Assistant users having the exact same problem, even worse than that no support from Shelly direct, they have even closed their own support forum thread - marked as resolved but no answer!

There is rumour of a new beta firmware but I have not seen it yet, I just thought I would highlight it and see if you had any advice?

Thanks
C

**Comment by smithy-eng** [comment]
More investigation while working with Shelly support that the issue is their side. The beta software did not fully work for me though.

**Comment by windkh** [comment]
is this solved in the meantime?
