### ISSUE TITLE
Support for Shelly Blu Wall Switch 4 via BLU-Gateway

### ISSUE THREAD

**Issue by johanneskropf** [windkh/node-red-contrib-shelly#181]
I have a BLU-Gateway which I use successfully for my BLU-Motion Sensors. I now got some of the new Shelly BLU Wall Switch 4's in hope of replacing my old Enocean Switches. The Shelly Node that is connected to my BLU-Gateway in callback mode correctly outputs a message for every time a button is pressed or released. The problem is that the data object I receive in nodered doesn't contain any information to distinguish which of the 4 buttons was pressed. This unfortunately makes the 4 way switch unusable right now. Is there any possibility to upgrade the script that is uploaded to the BLU-Gateway to also send the information which button was pressed to the Shelly-Node?
Thanks in advance, Johannes

**Comment by windkh** [comment]
Hi Johannes,
I just received my blu 4 button... will test it at the weekend. Stay tuned

**Comment by windkh** [comment]
Hi Johannes, I played around a bit and found out that the button property in the output is not the button number but the button event:
https://shelly-api-docs.shelly.cloud/docs-ble/Devices/wall_us/
<html>
<body>
<h3 class="anchor anchorWithStickyNavbar_LWe7" id="button-press-events" style="box-sizing: border-box; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-weight: var(--ifm-heading-font-weight); line-height: var(--ifm-heading-line-height); margin-top: calc(var(--ifm-h3-vertical-rhythm-top)*var(--ifm-leading)); margin-right: ; margin-bottom: calc(var(--ifm-heading-vertical-rhythm-bottom)*var(--ifm-leading)); margin-left: ; font-size: var(--ifm-h3-font-size); scroll-margin-top: calc(var(--ifm-navbar-height) + .5rem); --ifm-h3-font-size: 1.5rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Button press events<a href="https://shelly-api-docs.shelly.cloud/docs-ble/Devices/wall_us/#button-press-events" class="hash-link" aria-label="Direct link to Button press events" title="Direct link to Button press events" style="box-sizing: border-box; transition: opacity var(--ifm-transition-fast); color: var(--ifm-link-color); text-decoration: var(--ifm-link-decoration); opacity: 0; padding-left: 0.5rem; user-select: none;">​</a></h3>
id | name | example
-- | -- | --
0x00 | None | 0x3A00
0x01 | press | 0x3A01
0x02 | double_press | 0x3A02
0x03 | triple_press | 0x3A03
0x04 | long_press | 0x3A04
0xFE | button hold | 0x3AFE


</body>
</html>

**Comment by windkh** [comment]
Hm... I guess the Blu telegram which is received looks like

0x00 dib (Bit 0 : encryption = false, Bits 5ff BTHome_version = 2)
0x01 Type --> 0x3A
0x02 Value --> see table above 0x01, 0x02, 0x03, ...

But the same 0x3A is used in the same message several times as stated at the bottom here
https://shelly-api-docs.shelly.cloud/docs-ble/Devices/wall_us/

The bug is caused as the same value is overwritten 4 times .... so what you can see is button 4

**Comment by windkh** [comment]
BTHomeV2 is supported by shelly: see protocol here
https://bthome.io/format/

**Comment by windkh** [comment]
https://shelly-api-docs.shelly.cloud/gen2/Scripts/ShellyScriptLanguageFeatures/
describes BLE.Scanner.SCAN_RESULT

**Comment by windkh** [comment]
Hi @johanneskropf 
I found the solution and have it working here. The answer can be found in 
ble-shelly-blu.js in the examples provided by shelly. I will integrate a clean version of that tomorrow and release an update.
br kh

**Comment by johanneskropf** [comment]
Thanks for debugging this so quickly and getting to the bottom of it 🎉

**Comment by windkh** [comment]
@johanneskropf pleas test V11.4.0

**Comment by johanneskropf** [comment]
I have finally had time to test this and it works. Thanks you!

**Comment by windkh** [comment]
Alles klar danke für die info
