### ISSUE TITLE
Shelly type mismatch: S3PL-00112EU

### ISSUE THREAD

**Issue by FriKSlo** [windkh/node-red-contrib-shelly#182]
Hello,

Can you add this:
Shelly Plug S Gen3

Thank you.
Best regards!

**Comment by windkh** [comment]
Thanx for reporting ... will do

**Comment by windkh** [comment]
@FriKSlo this one?
https://kb.shelly.cloud/knowledge-base/shelly-plug-s-mtr-gen3

**Comment by FriKSlo** [comment]
Great. It works.
Thank you.
