### ISSUE TITLE
Input as array

### ISSUE THREAD

**Issue by MichaelSteg1986** [windkh/node-red-contrib-shelly#184]
Hello, is it possible to make an input array something like this.
[
    {
        "method": "Switch.Set",
        "parameters": {
            "id": 0,
            "on": true
        }
    },
    {
        "method": "Switch.Set",
        "parameters": {
            "id": 1,
            "on": true
        }
    }
]
Now it is only possible to set only one relay.
Thank you

**Comment by windkh** [comment]
I can add such a feature
