### ISSUE TITLE
Shelly Bulb 1 missing (Type mismatch: SHBLB-1)

### ISSUE THREAD

**Issue by UZone007** [windkh/node-red-contrib-shelly#185]
Hi,

i am using a old Shelly Bulb 1 (not Duo) like this one: 
https://www.ktek.me/product/shelly-bulb/SHL-BB

I am using nodered. All my other shelly devices work fine.
The Shelly Bulb 1 works aswell, when i select the "Bulb RGBW" type, but i always get a message "type mismatch: SHBLB-1".

I think you just had to add the type SHBLB-1 in your script.
The Shelly Bulb 1 is also a RGBW bulb.

Thanks for your work.
Among all librarys, yours is the best one to use for me and all my other shellys work flawless.
![NodeRed_Screen](https://github.com/user-attachments/assets/ad01f9d7-2ab3-485d-824a-ad3813c1bf96)
[NoderRed_export.txt](https://github.com/user-attachments/files/17423202/NoderRed_export.txt)

**Comment by windkh** [comment]
@UZone007 please test if it works with the next version thanks for reporting

**Comment by UZone007** [comment]
![grafik](https://github.com/user-attachments/assets/94686528-adef-48f3-bf69-509ee7a456fd)

@windkh thanks for the fast update.
I tried the new v11.4.1 but i still get the same error message.

**Comment by windkh** [comment]
it is 11.4.2

**Comment by UZone007** [comment]
oh right. but it shows still the same error message

![grafik](https://github.com/user-attachments/assets/b1beb07f-7e88-43d2-b0ea-738308edaf97)

**Comment by UZone007** [comment]
![grafik](https://github.com/user-attachments/assets/b7954d60-abf7-4737-8f4b-c8eb15005452)
 this works!!
 just saw there is a new category
 thank you so much
