### ISSUE TITLE
Second Shelly UNI stops reporting

### ISSUE THREAD

**Issue by PowerZone21** [windkh/node-red-contrib-shelly#187]
Hi,

I got two Shelly UNI's. 
The first one have one DS18B20 temp sensor. Connected to Noe Red and works perfect! Reporting temp contantly.

The second one have two DS18B20 temp sensors. Also connected to Node Red and works for a period, then stops reporting to Node Red. When I force 'Get Status' from NR, it reports correct temp, but not automaticly when temp changes.

iPhone Shelly app works perfect and any temp changes are shown always.

I use the same notwork port (1883) for both, but name and IP are different

What could cause this issue?

**Comment by windkh** [comment]
Have you used callback mode?

**Comment by PowerZone21** [comment]
I think I have a solution for this issue.
The inputs were activated, but non in use.
When I deactivated the inputs, problems seems to be gone :)
