### ISSUE TITLE
Shelly type mismatch: SPSW-201XE15UL

### ISSUE THREAD

**Issue by leifels-inf** [windkh/node-red-contrib-shelly#188]
Using Node-Red adding a Shelly Pro 1 node from node-red-contrib-shelly fails with 
              "Shelly type mismatch: SPSW-201XE15UL. 
              Choose correct type or if the device is not supported yet then report it here: 
              https://github.com/windkh/node-red-contrib-shelly/issues"

Best Regards
Andreas

**Comment by windkh** [comment]
@leifels-inf 
Hi Andreas, thanks for reporting.
There are already some versions of the Shelly Pro 1 in the config
- "Shelly Pro 1",         "model" : "SPSW-001XE16EU"
- "Shelly Pro 1 v.0",     "model" : "SPSW-101XE16EU",
- "Shelly Pro 1 v.1",     "model" : "SPSW-201XE16EU"
-

So I guess yours will be something like
- "Shelly Pro 1 v.1 UL",     "model" : "SPSW-201XE15UL"

I will add this to the configuration asap!

**Comment by windkh** [comment]
BTW UL stand for "Underwriters Laboratories". It is a required certificate for North-America and Canada.
