### ISSUE TITLE
Shelly Plus RGBW PM - Documentation irritating

### ISSUE THREAD

**Issue by mvondemhagen** [windkh/node-red-contrib-shelly#189]
Just in case somebody else tries to control a Shelly Plus RGBW PM via this in white mode:

The payload to control needs to look as follows:
```
msg.payload = {
    method: "Light.Set",
    parameters : {
        id : 0,
        on: true,
        brightness: 100,
    }
};
return msg;
```
Using the method "RGBW.Set" doesn't work here. id: {0..3} addresses the four channels.

**Comment by windkh** [comment]
So RGBW.Set only works in colour mode then?

**Comment by mvondemhagen** [comment]
I guess so, I don't have that device in RGB(W) mode, so can't test. Just have been spending a few hours to get white mode running, with a function as above it finally works.

**Comment by mvondemhagen** [comment]
![SCR-20241109-uoon](https://github.com/user-attachments/assets/2de58ab4-bde7-431b-9132-0ba722f97952)

Just to make sure, this is the mode I'm talking about. Technically, it'd be possible to attach four different white LED strips to the device and control them via RGBW.Set in RGBW-mode, but then they wouldn't be id:{0..3} but the respective RGBW values. Not recommended.
