### ISSUE TITLE
Shelly type mismatch: S3SW-002P16E for Shelly 2PM Gen3 is missing

### ISSUE THREAD

**Issue by leifels-inf** [windkh/node-red-contrib-shelly#190]
Errorreport:
"Shelly type mismatch: S3SW-002P16EU. Choose correct type or if the device is not supported yet then report it here: https://github.com/windkh/node-red-contrib-shelly/issues"

The type S3SW-002P16EU is not yet available as Devicetype in Node-Red node of type "shelly gen2 +"

**Comment by windkh** [comment]
@leifels-inf thanks for reporting... will add this this evening.
Is it that one? https://kb.shelly.cloud/knowledge-base/shelly-2pm-gen3

**Comment by leifels-inf** [comment]
Yes, this is the o n e :> 
 
*         Device name: Shelly 2PM Gen3
*	Device model: S3SW-002P16EU
 
Best regards
 
Andreas
 
 
Von: Karl-Heinz Wind ***@***.*** 
Gesendet: Montag, 11. November 2024 15:24
An: windkh/node-red-contrib-shelly ***@***.***>
Cc: leifels-inf ***@***.***>; Mention ***@***.***>
Betreff: Re: [windkh/node-red-contrib-shelly] Shelly type mismatch: S3SW-002P16E for Shelly 2PM Gen3 is missing (Issue #190)
 
@leifels-inf <https://github.com/leifels-inf>  thanks for reporting... will add this this evening.
Is it that one? https://kb.shelly.cloud/knowledge-base/shelly-2pm-gen3
