### ISSUE TITLE
Shelly BLU Gateway Gen3

### ISSUE THREAD

**Issue by hollenal** [windkh/node-red-contrib-shelly#191]
New device type that is not recognised / supported yet.
Let me know if I can be of any assistance.

**Comment by windkh** [comment]
@hollenal 
What device is it? Can you send me the output of the device info: 
 http://ip-of-your-shelly-here/shelly

and maybe a link to the device in the shelly shop or from here 
https://kb.shelly.cloud/knowledge-base/devices

**Comment by hollenal** [comment]
@windkh 

Sure. Here you go:
{
    "name": null,
    "id": "shellyblugwg3-34cdb077xxxx",
    "mac": "34CDB077XXXX",
    "slot": 1,
    "model": "S3GW-1DBT001",
    "gen": 3,
    "fw_id": "20241021-140344/1.4.99-blugwg3prod4-g110402b",
    "ver": "1.4.99-blugwg3prod4",
    "app": "BluGwG3",
    "auth_en": false,
    "auth_domain": null
}

https://kb.shelly.cloud/knowledge-base/shelly-blu-gateway-gen3

**Comment by windkh** [comment]
@hollenal please check version V11.5.3 and report if it worked.

**Comment by hollenal** [comment]
@windkh Gateway was detected and scripts successfully installed
