### ISSUE TITLE
Dimmer - option to disable 'status requests'

### ISSUE THREAD

**Issue by Paul-Reed** [windkh/node-red-contrib-shelly#21]
I'm using automated and slider controls to vary the brightness of a shelly dimmer, some of the changes occur at a fast rate to create a smooth lighting transition, but because the shelly node requests a 'status request' after each step in the transition, the poor shelly can't keep pace, and eventually crashes, requiring a shelly reboot.

By having a node config option to disable the 'status requests', the demand on the shelly dimmer is significantly reduced, and then works reliably.
There is then an opportunity to update the google homegraph by pushing a blank payload into the shelly node to get the status when necessary.

I have this working now, and will submit a PR for your consideration in the next few days.
(The default setting is 'status report enabled)

![shell](https://user-images.githubusercontent.com/973580/116796526-05620d00-aad5-11eb-81f1-ac2832b4695d.JPG)

**Comment by Paul-Reed** [comment]
PR submitted for consideration please.

**Comment by windkh** [comment]
merged into 1.6.0
