### ISSUE TITLE
Shelly EM and EM3

### ISSUE THREAD

**Issue by MyCodeRocks** [windkh/node-red-contrib-shelly#26]
Hi there,

Awesome work and thank you. I have a bunch of the power meters Shelly EM (single phase) and EM3 (Three Phase). Would love to contribute to help you add to this, would you be interested. If yes what would you need? I could also do some testing

**Comment by windkh** [comment]
Sorry for delay, I just read your request.
I would need to buy such a device first to be able to test.

Maybe we could start with  the code from the shelly door node as a skeleton as it already polls for the door data.
I guess polling the data from a EM should be almost equal. Maybe you could support me in testing?

**Comment by windkh** [comment]
I ordered both devices today ... stay tuned

**Comment by MyCodeRocks** [comment]
Hey there, I will test anything you need me to and provide any info you need to :) all you have to tell me is what you need :)

**Comment by windkh** [comment]
@MyCodeRocks I ordered the hardware myself… just wait until I get my hands on it

**Comment by windkh** [comment]
version 1.10.0 should support EM (EM3 not tested)

**Comment by windkh** [comment]
version 1.10.1 should support also EM3.
