### ISSUE TITLE
Please add support for Shelly Door/Window2 and Shelly Button

### ISSUE THREAD

**Issue by mschuricht** [windkh/node-red-contrib-shelly#27]
Please add support for Shelly Door/Window2 and Shelly Button, Thank you.

**Comment by windkh** [comment]
Door is supported alrready. Did you try it out?

A button is a litte bit different as it only sends data to other devices. What would you need?
Should I create a node that receives incoming data from a button? So that you can react on it?

**Comment by windkh** [comment]
no response from author
