### ISSUE TITLE
Cannot see all the status information on my Shelly Plug S

### ISSUE THREAD

**Issue by MrChunks** [windkh/node-red-contrib-shelly#28]
First, I will say that I'm really new to this, so it's likely I'm doing something wrong. I apologize if that's the case here.

To my issue: I have a few Shelly Plug S smart plugs, and I was looking to read some data off them - specifically, the power usage. This info DOES appear to be in the "/status" json on the smart plug, but when I try to view msg.status in node red, I get "undefined".

Debugging the response just shows it containing a payload object (with messageid), but nothing else. Is that enough info? Thanks for any help.

**Comment by windkh** [comment]
@MrChunks please enable complete msg object in debug node.
Then you can see that msg.status contains what you are searching for

![image](https://user-images.githubusercontent.com/10910767/127050256-55c06c21-adb1-4a3d-8427-92cf6d0205ca.png)

**Comment by MrChunks** [comment]
Thanks for replying... I hope it's something that obvious, but it doesn't seem to be the case (unless I'm truly missing something basic, In which case, I'm sorry.)

I can't see the status at all. I've created 3 separate  debug nodes. The first is just..... to make sure I'm not screwing up something so basic. The second two should both contains msg.status but it seems that they don't. Should I be troubleshooting something else? Again, thanks for having a look.

![image](https://user-images.githubusercontent.com/15183323/127204963-6b0756d3-0949-48d7-9a79-0cce91887c9c.png)

**Comment by windkh** [comment]
Here is my output
![image](https://user-images.githubusercontent.com/10910767/127209257-3784a89f-8915-4f5f-b059-6004016458e3.png)

**Comment by windkh** [comment]
With this FW
![image](https://user-images.githubusercontent.com/10910767/127209368-ce9e496f-0d2b-4e07-b1f8-a813618465eb.png)

**Comment by MrChunks** [comment]
Well! You're right it works. 

I setup Node-RED ages ago, including this Shelly plugin. I never updated it. I expected some sort of popup "your palette's have updates!" ... never considered I was running old code. 

In short, update to the latest version before opening bug reports :( Sorry for taking your time, but thanks for providing the info and screenshots.

**Comment by windkh** [comment]
@MrChunks you are welcome
