### ISSUE TITLE
Add support for cloud API

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-shelly#29]
see https://shelly.cloud/documents/developers/shelly_cloud_api_access.pdf

**Comment by windkh** [comment]
I guess there should be extra nodes for that

**Comment by windkh** [comment]
Hallo @HWiese1980 
ich hab die Nachricht nicht ganz verstanden.

Die cloud api ist ein komplett anderer Zugang.
Dieser hat mit der bot api nichts zu tun.
Es würde nur Sinn machen ein komplett neues projekt mit eigenen Nodes zu erstellen. 

Macht das Sinn? Braucht das jemand?

**Comment by HWiese1980** [comment]
Macht aus meiner Sicht durchaus Sinn, weil's meines Wissens noch keine Integration gibt, die die Shelly Cloud API nutzt. Ich hatte die Issue (wegen der Überschrift) so verstanden, dass du genau das machen wolltest.

**Comment by windkh** [comment]
Ok dann schau ich mal was ich machen kann.

**Comment by HWiese1980** [comment]
Das klingt gut! 

Ich hab damit auch schon etwas rumgespielt. Schalten von Relays ist wirklich einfach. Was eine Herausforderung ist, und das wäre als Feature auch echt cool, ist die Verbindung zum WebSocket Endpunkt der API für Status-Updates. Das hab ich so ohne Weiteres jetzt noch nicht hinbekommen - auch aber, weil ich's noch nicht wirklich verfolgt habe. Bislang hab ich nur über Node-Red mittels POST Request ein Relais geschaltet.

**Comment by windkh** [comment]
First version can be used to get the raw status of the device.

TODO:
- documentation
- control
- bulkcontrol
- real time events

**Comment by HWiese1980** [comment]
Sehr cool. **Danke!** Werd ich gleich mal ausprobieren.
