### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by ahartman** [windkh/node-red-contrib-shelly#30]
At every poll I see an error ENOTFOUND as in image below. The device works fine, why the error?
I use latest versions of module and of Shelly 1 firmware.

<img width="386" alt="Schermafbeelding 2021-09-14 om 10 26 49" src="https://user-images.githubusercontent.com/688316/133223501-aa252296-8d95-4934-b45e-5f1379ec1115.png">

**Comment by windkh** [comment]
Hm strange, what did you enter? An IP Adress or a hostname?
What node is it?

**Comment by ahartman** [comment]
Dear Karl-Heinz,

I entered an IP address, since hostnames are not working for me.
I tried hostnames f3d414 and f3d414.local and neither works.

I just looked again and the particular switch is now stable after it has shown that error for several hours.

Again, during the occurrence of the error, I could control the switch from Node-Red without any issuers.

Kind regards, ahartman, belgium

**Comment by windkh** [comment]
@mmierke can I send you a flow for testing?

**Comment by mmierke** [comment]
I have disabled the flow now, but the issue still appears in the disabled flow.

**Comment by windkh** [comment]
ok then I will close the issue.
