### ISSUE TITLE
Support for Bulb Duo RGBW

### ISSUE THREAD

**Issue by jzeeman01** [windkh/node-red-contrib-shelly#32]
Hi Is there any plans to support the bulb range - looking at the Bulb Duo RGBW specifically?
Thx for the great work!
Jacques

**Comment by windkh** [comment]
Hm I can do it if you want.
I need to order this device first... so it will take some time.

**Comment by jzeeman01** [comment]
Awesome - Much appreciated

**Comment by windkh** [comment]
The device can be delivered after 10. Nov... so we have to wait

**Comment by windkh** [comment]
If you are lucky the RGBW node could work if you turn polling offGesendet mit der WEB.DE iPad AppAm 01.11.21 um 16:26 schrieb jzeeman01
                
            
            
                
                    Von: "jzeeman01" ***@***.***>Datum: 1. November 2021An: "windkh/node-red-contrib-shelly" ***@***.***>Cc: "Comment" ***@***.***>,"Karl-Heinz Wind" ***@***.***>Betreff: Re: [windkh/node-red-contrib-shelly] Support for Bulb Duo RGBW (Issue #32)
                
                
No Problem at all
I've got it working via MQTT but its a bit fiddly because of the the white and color settings, one working with gain and the other with brightness etc.

**Comment by jzeeman01** [comment]
By polling do you mean the ping interval in the node or another setting in the device itself?
I tried with the ping interval but still get the "Shelly type SHCB-1 is not known"
Rgds
J

**Comment by windkh** [comment]
Set ping interval to 0 and let me know what happensGesendet mit der WEB.DE iPad AppAm 01.11.21 um 20:09 schrieb jzeeman01
                
            
            
                
                    Von: "jzeeman01" ***@***.***>Datum: 1. November 2021An: "windkh/node-red-contrib-shelly" ***@***.***>Cc: "Karl-Heinz Wind" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [windkh/node-red-contrib-shelly] Support for Bulb Duo RGBW (Issue #32)
                
                
By polling do you mean the ping interval in the node or another setting in the device itself?
I tried with the ping interval but still get the "Shelly type SHCB-1 is not known"
Rgds
J

**Comment by jzeeman01** [comment]
Hi - thats what I did - still got the "Shelly type SHCB-1 is not known" error
Rgds
J

**Comment by windkh** [comment]
Ok thanks

Von meinem iPhone gesendet

**Comment by windkh** [comment]
supported in 1.13.0

**Comment by jzeeman01** [comment]
Brilliant
The easy way to poll the status is awesome too
Thx for all the work
Jacques
