### ISSUE TITLE
Please add support for shelly plus 1

### ISSUE THREAD

**Issue by KasimirGuenter1259** [windkh/node-red-contrib-shelly#41]
I have tried to connect to an _**shelly plus 1**_ using the switch node.

Unfortenately my complete node red instance was corrupted. I've tried this several times. Always the node red instance is corrupted. node red could not be restarted. I must **deinstall** node red and a complete **reinstall** of node red.
This could be reproduced.

**Comment by windkh** [comment]
How can I reproduce it?

**Comment by KasimirGuenter1259** [comment]
Hi,
ich schreibe erst auf deutsch, weil: 

My English is not the yellow from the egg!

Es genügt folgendes Vorgehen, um den Fehler zu reproduzieren:

1. Einfügen eines shelly  _switch_ nodes
2. Eintragen der IP-Adresse eines **_shelly plus 1_** Gerätes
3. Drücken auf den Button _deploy_

Und das Node Red System ist im Nirwana. Die CPU GesamtLast steigt von ca 3-4% auf ca 30%, die CPU Temperatur steigt um 5-6°. Das Node Red System reagiert kaum noch .....  

Beim Versuch Node Red zu stoppen und neu starten, laufen die immer gleichen Fehlermeldungen in Endlosschleife durch. Das Node Red kann nicht mehr gestartet werden. Eine komplette Neuinstallation ist notwendig.

Ich habe das mehrfach gemacht. Das ist (zumindest bei mir) reproduzierbar und liegt definitiv am shelly switch node in Verbindung mit einem shelly plus 1 Gerät. (Nur zur Klarstellung: ich bin inzwischen Fan der shelly Geräte und habe viele shelly 1 und shelly 2.5 sowohl zum Schalten von Geräten als auch zur Jalousiesteuerung im Einsatz. Funktioniert alles hervorragend und zuverlässig.)

Meine Umgebung:

- Hardware: Raspberry Pi 4B
- aktuelles Buster Betriebssystem (aktualisiert mit apt-get update und apt-get upgrade)
- Node Red v2.1.3
- shelly nodes Version 2.0.0

**I try in English (short form):**
Reproducing is possible with following steps:

1. Insert a new shelly _switch_ node
2. Insert the IP-Adress of a _shelly plus 1_ device
3. click the node red button _deploy_

The node red system is hanging. 
If i try to restart the node red system, this is not possible.
I have to deinstall node red and then a new installation must be done.

**Comment by windkh** [comment]
Ah ok again what learned. Tja there can you nothing make. 
hab keinen shelly plus muss erst einen besorgen

**Comment by windkh** [comment]
Ok I found one: the new generation has a different protocol:

![image](https://user-images.githubusercontent.com/10910767/142768782-a00dce13-d272-4195-bffe-ee1e2ee60ca7.png)

**Comment by windkh** [comment]
New
`
{
    "id":"shellyplus1pm-44179394b8d0", 
    "mac":"44179394B8D0", 
    "model":"SNSW-001P16EU", 
    "gen":2, 
    "fw_id":"20210921-202918/0.8.1-g52de872", 
    "ver":"0.8.1", 
    "app":"Plus1PM", 
    "auth_en":false,
    "auth_domain":null
}
`

**Comment by windkh** [comment]
I will create a new switch node for gen 2 that supports the new protocol:
https://shelly-api-docs.shelly.cloud/gen2/

**Comment by windkh** [comment]
version 2.1.0 supports it
