### ISSUE TITLE
Shelly 2.5 in Relay Mode is not working

### ISSUE THREAD

**Issue by lecim** [windkh/node-red-contrib-shelly#43]

**Comment by windkh** [comment]
Can you please specify what you did and what does not work?

**Comment by lecim** [comment]
The Shelly 2.5 ist configured as relay.

![image](https://user-images.githubusercontent.com/48917052/143720170-66b82407-aa98-45d4-9af8-c9ab6e8a32d6.png)

According to the shelly API i had expected that i had to send the payload {relay:0, on:true}, which is not working. I've tried roller:0 and id:0 with no result.

The Status response in node red after sending an empty payload looks like:
![image](https://user-images.githubusercontent.com/48917052/143720285-7de7c3c2-bf5c-486d-bdba-d092ed48c8f3.png)

**Comment by windkh** [comment]
Yes that is not implemented yet. Do you need this?

**Comment by lecim** [comment]
Would be great.
Looking at the code, i guess it is a mix  of the type check of the roller node and the logic of the switch node.

**Comment by windkh** [comment]
Yes indeed it should be quite simple…. I will do it today

**Comment by lecim** [comment]
Work's like a charm

**Comment by windkh** [comment]
:)
