### ISSUE TITLE
Dynamic Colour/White device selection

### ISSUE THREAD

**Issue by jzeeman01** [windkh/node-red-contrib-shelly#44]
Hi
For the Bulb Duo RGBW you have to select either the Color / White
Is it possible to pass this as a variable from msg object e.g. msg.topic?
Thx again for the great work
J

**Comment by windkh** [comment]
I would have to reconfigure the shelly via the API… i will try to implement it

**Comment by windkh** [comment]
version 3.3.0 supports this

**Comment by jzeeman01** [comment]
Amazing!!! thx
