### ISSUE TITLE
Shelly plug S error

### ISSUE THREAD

**Issue by henneonrails** [windkh/node-red-contrib-shelly#46]
my shelly plug s behaves like this:
![Bildschirmaufnahme-2021-12-21-um-05 57 14](https://user-images.githubusercontent.com/123651/146874378-8aea3960-ecbc-48e5-99de-9e041eba4c5c.gif)
my other shelly devices like shelly 1 behave like expected.

**Comment by windkh** [comment]
What version of the lib do you use? 
please send me the flow so that I can reproduce it with one of my plug s devices.

**Comment by henneonrails** [comment]
### i am using this versions
node-red-contrib-shelly version 3.4.0
redmatic 7.2.1 on ccu-3
shelly plugs firmware 20211109-130223/v1.11.7-g682a0db 

I did not set up a flow with the plug, mainly I wanted to see it in Apple HomeKit.

**Comment by windkh** [comment]
What polling interval did you use?

**Comment by henneonrails** [comment]
5000 ms

**Comment by windkh** [comment]
Then can you export that single node and paste it here?

**Comment by henneonrails** [comment]
`[{"id":"9b4e7034.e3d178","type":"shelly-switch","z":"f99e761a.c6c0e8","hostname":"192.168.178.67","description":"","pollinginterval":5000,"x":570,"y":1220,"wires":[[]]}]`

**Comment by henneonrails** [comment]
I have seen, if I connect a switch node from the redmatic HomeKit to the plug node, then the connection error cycle is gone.

**Comment by windkh** [comment]
Ah ok does the redmatic node the same?

**Comment by henneonrails** [comment]
`[{"id":"9b4e7034.e3d178","type":"shelly-switch","z":"f99e761a.c6c0e8","hostname":"192.168.178.67","description":"Shelly plugS","pollinginterval":5000,"x":890,"y":1220,"wires":[[]]},{"id":"3bd34e86.3aa75a","type":"change","z":"f99e761a.c6c0e8","name":"Ändern Nachricht","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"{\"relay\":0,\"on\":true}","tot":"json"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"{\"relay\":0,\"on\":false}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":1220,"wires":[["9b4e7034.e3d178"]]},{"id":"553a2f84.1c54c8","type":"redmatic-homekit-switch","z":"f99e761a.c6c0e8","bridgeConfig":"a5f6fb99.cec568","name":"Weihnachtsbaum","x":350,"y":1220,"wires":[["3bd34e86.3aa75a"]]},{"id":"a5f6fb99.cec568","type":"redmatic-homekit-bridge","name":"RedMatic Bridge","username":"CC:22:3D:9B:25:BD","pincode":"834-44-574","port":"51826"}]`

No everything work like expected when the nodes are connected. Expect the old problem of getting the right state of the Shellys back to HomeKit. Often they show as "off" while they are switched "on" (in HomeKit).

**Comment by windkh** [comment]
I have an idea what could have happened. 
The error says: ENOTFOUND **http**
The rest is not visible however http seems to be wrong as it must be an IP address or a hostname. Maybe you copied the address from the browser into the hostname field and wrote something like this?

![image](https://user-images.githubusercontent.com/10910767/147150476-e81eacbb-e077-422d-9c8c-8e85016aa30e.png)

**Comment by ucel** [comment]
I have the same error with Shelly RGBW:

![image](https://user-images.githubusercontent.com/21318942/154823703-834ed0d6-62db-496b-b16d-6af5df19f765.png)

Error on the picture is displayed a part of the second, then switches to green "Connected". 
I have also configured Shelly 1 and Shelly 2 integrations and both are working without problems.

**Comment by windkh** [comment]
@ucel can you reproduce it so that we can debug it?

**Comment by windkh** [comment]
can you please try 4.5.0 and check if it is gone?

**Comment by ucel** [comment]
I could update to version 4.4.0, but the error persists.

**Comment by windkh** [comment]
4.6.0 is available (maybe soon) see https://flows.nodered.org/node/node-red-contrib-shelly

Can you send me your flow so that I can try to reproduce it?

**Comment by ucel** [comment]
With this flow:

> [{"id":"8d91a20d.ce7af","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"7a27cdcb.c33944","type":"shelly-rgbw2","z":"8d91a20d.ce7af","hostname":"192.168.2.233","description":"","ledStat":true,"pollinginterval":5000,"mode":"color","pollstatus":false,"x":600,"y":100,"wires":[[]]},{"id":"34c65b87.abd8a4","type":"function","z":"8d91a20d.ce7af","name":"On","func":"\nreturn {payload : {on: true}};","outputs":1,"noerr":0,"x":360,"y":100,"wires":[["7a27cdcb.c33944"]]},{"id":"ee77c941.3e7918","type":"inject","z":"8d91a20d.ce7af","name":"On","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":100,"wires":[["34c65b87.abd8a4"]]},{"id":"9917cd87.9144b","type":"function","z":"8d91a20d.ce7af","name":"Off","func":"\nreturn {payload : {on: false}};","outputs":1,"noerr":0,"x":350,"y":180,"wires":[["7a27cdcb.c33944"]]},{"id":"2b8fee23.d68682","type":"inject","z":"8d91a20d.ce7af","name":"Off","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":180,"wires":[["9917cd87.9144b"]]}]

I can switch off of the light, but while trying to switch in on I get the error like above. Tried just now with 4.6.0.

**Comment by windkh** [comment]
@ucel ok I think I found the problem... will fix it in next version. Thanks. 


Reason: the payload 'return {payload : {on: true}};' was treated as empty as no color nor brightness was given... I never thought that someone will leave all the other properties except for the on one away

**Comment by windkh** [comment]
moved to new issue

**Comment by windkh** [comment]
@ucel should be fixed in 4.7.1

**Comment by ucel** [comment]
It's working, thanks!
