### ISSUE TITLE
Output is triggered after every poll cycle

### ISSUE THREAD

**Issue by rallep71** [windkh/node-red-contrib-shelly#47]
Hi,

I don't think it's a good idea that the status is constantly triggered at the output, at least there should be the possibility to turn this off and set a time interwall.

I have to filter this constant output trigger in a cumbersome way!

**Comment by windkh** [comment]
I will add a flag for that

**Comment by rallep71** [comment]
Ok, but otherwise it's a great node, thanks for the work!

**Comment by rallep71** [comment]
perhaps I have not expressed myself correctly,

if I manually query a status, this should still work, the other two flags should then be a time interval, on the other hand this should also be able to be switched off completely without preventing the manual status query, thx

**Comment by windkh** [comment]
understood... however you should set the polling interval to 0 in your use case as you are only triggering it yourself, or?

**Comment by rallep71** [comment]
richtig, ok, setze es auf 0 ;) danke schon mal

**Comment by windkh** [comment]
Version 4.1.0 should fix this

**Comment by rallep71** [comment]
Thx,it work!!!
