### ISSUE TITLE
Shelly i3

### ISSUE THREAD

**Issue by SpaceRichard** [windkh/node-red-contrib-shelly#50]
Hi @windkh 

any plan to support the Shelly i3?
Or is there a reason why this is not supported yet?

Thanks
Richard

**Comment by windkh** [comment]
Hi … the reason is quite simple. I do not own a I3.
Whenever I buy a device I implement the node red node to support it.
… I can not affort buying all devices in the shop at the same time.

**Comment by SpaceRichard** [comment]
As it's no longer on sell, I guess it will never be supported.
Thanks for your answer.

**Comment by windkh** [comment]
You can send me one. Then I can test the implementation and afterwards I send it back to you. That is all
i can offer

**Comment by windkh** [comment]
Another idea: I guess the I3 is similar to the shelly button but with more channels.
I could create a button node and you would have to test if it also works with your I3.
What about that?

**Comment by SpaceRichard** [comment]
We could try this. I send you already an email. But let’s try the solution and I will test it here.

**Comment by windkh** [comment]
I did not receive an emai

**Comment by SpaceRichard** [comment]
I send it to the web.de address linked in your profile. Maybe it’s sorted as spam?

**Comment by windkh** [comment]
please check out 4.4.0
