### ISSUE TITLE
Problems after installing 4.1.4

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-shelly#51]
Introducing the scorecards people reported problems after upgrading to 4.1.4
Please let me know if there are more who discovered that.
What node-red version and what nodejs version do you have?

**Comment by Harryx99** [comment]
Hi.

I have "node-red": "1.2.9" in the Redmatic packet. It looks like the new shelly node is not compatible with this node red version? 

regards,
Holger

**Comment by Harryx99** [comment]
Will test it when it's showing in Node Red. At the moment it's version 4.3.0 available only ;)

**Comment by windkh** [comment]
Well then I do not have any clue what is going on as I removed the changes in package json that caused the problems completely. 
It seems there is a serious problem inside redmatic...  

similar problems occured when I made the same changes in telegrambot see
https://github.com/windkh/node-red-contrib-telegrambot/issues/235

**Comment by windkh** [comment]
@Harryx99 
Can you restart redmatic and install the latest version?

**Comment by Harryx99** [comment]
Now it works, Shelly's are back ;) 

Thanks a lot
