### ISSUE TITLE
Setting an empty hostname does not deactivate polling and results in an error

### ISSUE THREAD

**Issue by hashworks** [windkh/node-red-contrib-shelly#54]
According to the README, setting an empty hostname results in disabled polling and allows one to set the hostname using the payload. However, this doesn't work:

![img-2022-02-21-142905](https://user-images.githubusercontent.com/2362091/154964945-869d9c9f-1f62-4753-909d-f26b38a8a0c5.png)
![img-2022-02-21-142919](https://user-images.githubusercontent.com/2362091/154964975-15615d2e-f43d-4ec6-b1e9-7cefa1828cc2.png)
![img-2022-02-21-142752](https://user-images.githubusercontent.com/2362091/154964989-c5702443-5eda-480f-a73a-f96dbb94911b.png)
![img-2022-02-21-142849](https://user-images.githubusercontent.com/2362091/154965009-3dbd6c44-1ee1-4723-8ee2-396cace416fe.png)

I think this happens because it [tests if the hostname is `undefined` but it's an empty string instead](https://github.com/windkh/node-red-contrib-shelly/blob/d48ba3806c104cdd873d7404415bcd1937e72f6c/shelly/99-shelly.js#L19).

**Comment by windkh** [comment]
@hashworks hi thanks for reporting, however I can not reproduce it. Can you send me your flow?

**Comment by windkh** [comment]
btw I guess that passing user and password is not supported yet, but that can be done if you need it.

**Comment by hashworks** [comment]
A simple flow with only a switch node fails instantly:
```json
[{"id":"df6ac3a2631c1edb","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"e058bc20a0f20823","type":"shelly-switch","z":"df6ac3a2631c1edb","hostname":"","description":"","x":520,"y":260,"wires":[[]]}]
```

![img-2022-02-21-211809](https://user-images.githubusercontent.com/2362091/155021313-db1e5487-ceb7-44b7-ae57-71a4897e8923.png)

**Comment by hashworks** [comment]
Ah, nevermind – I was missing an update. My bad!
