### ISSUE TITLE
Bug or feature? "toggle_after “ in function node payload

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#61]
Hello,

Thanks for a very useful node!
One issue I see is that the node appears to act in an unintended way when using the
"toggle_after “ function in the node payload. I might be misunderstanding the intended functionality
but here is an example:

If I want to set a Shelly 1PM plus relay to switch off and then switch back on after X secs (very important feature in my work)
This is the code that this node red flow example suggest we use:
```
msg.payload = {
    id : 0, 
    on : false,
    toggle_after : 2
};
return msg; 
```
This will indeed switch the relay off, as indicated but will not switch it back on after 2 secs.
If I however send the payload again when the relay is off, it will switch back on.
This seems wrong but please let me know if I am misunderstanding something or if this is a a bug?
The Shelly 1pM plus I am testing with has firmware 0.10.0
Many thanks.

**Comment by windkh** [comment]
Hm I just send that flag to the shelly … I will try to reproduce it.

**Comment by houser42** [comment]
> Hm I just send that flag to the shelly … I will try to reproduce it.

Great, thanks @windkh 
I look forward to your reply. Let me know if I can test something. Many thanks!

**Comment by windkh** [comment]
@houser42 it works in both directions on --> off after 2s and off --> on after 2s

I tested it using this flow

[{"id":"7899c86207400f26","type":"debug","z":"f45ce90b3151803b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":770,"y":440,"wires":[]},{"id":"9d972196920e1ce5","type":"function","z":"f45ce90b3151803b","name":"0 on","func":"msg.payload = {\n    id : 0,\n    on : true,\n    toggle_after : 2 // optional flip back time in seconds\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":330,"y":440,"wires":[["2c6bffe0d8827f5f"]]},{"id":"3b2db8394dc6ea85","type":"function","z":"f45ce90b3151803b","name":"0 off","func":"msg.payload = {\n    id : 0, \n    on : false,\n    toggle_after : 2 // optional flip back time in seconds\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":330,"y":500,"wires":[["2c6bffe0d8827f5f"]]},{"id":"72b2ecfbb65b923b","type":"inject","z":"f45ce90b3151803b","name":"Turn On","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":204.99413108825684,"y":440.193359375,"wires":[["9d972196920e1ce5"]]},{"id":"2972b780145b01f1","type":"inject","z":"f45ce90b3151803b","name":"Turn Off","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":500,"wires":[["3b2db8394dc6ea85"]]},{"id":"5aa54bfb2f16f55c","type":"inject","z":"f45ce90b3151803b","name":"Poll Status","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":380,"wires":[["2c6bffe0d8827f5f"]]},{"id":"2fdb598c3a9f0e8e","type":"function","z":"f45ce90b3151803b","name":"0 toggle","func":"msg.payload = {\n    id : 0, \n    method: \"Switch.Toggle\"\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":340,"y":560,"wires":[["2c6bffe0d8827f5f"]]},{"id":"1597a10879f722a3","type":"inject","z":"f45ce90b3151803b","name":"Toggle","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":190,"y":560,"wires":[["2fdb598c3a9f0e8e"]]},{"id":"2c6bffe0d8827f5f","type":"shelly-gen2","z":"f45ce90b3151803b","hostname":"192.168.178.242","description":"","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":true,"devicetype":"Relay","outputs":1,"x":530,"y":440,"wires":[["7899c86207400f26"]]}]

**Comment by windkh** [comment]
@houser42 did you check if the latest firmware is used. What version of the nodes do you use?

**Comment by houser42** [comment]
Hello @windkh 
As mentioned, I have the latest versions of either. 7.1.0 of the node and 0.10.0 of the Shelly 1 PM plus relay.

I tried to test your flow but it its giving me an error when attempting to import into Node Red.
"SyntaxError: JSON Parse error: Expected '} 
I am unable to figure out how to fix the formatting.
Would love to test it!

This is what JSON formatter gives:

`Error: Parse error on line 104:
... : 0, \n method: "	Switch.Toggle "\n};\
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'`

**Comment by windkh** [comment]
[flows.zip](https://github.com/windkh/node-red-contrib-shelly/files/8330402/flows.zip)

I had to zip it as github refused the file extension

**Comment by houser42** [comment]
Thanks @windkh 
Yes, that works here also. Many thanks!
Must have been something wrong with the flow I used.
May I also ask if it is possible to use flip back on and flip back off after x secs.  rather than toggle with this node? As you can withMQTT.
If so what is the suggested payload? There is no example here that I can see? Many thanks again.

**Comment by windkh** [comment]
@houser42 hm… to be honest I do not know how the API calls interfere with MQTT as I never used it in both ways at the same time

**Comment by houser42** [comment]
Thanks again @windkh 
I would also prefer to only use your node..
The only thing missing for my purposes is the ability to be able to override an auto on set on the relay with a 
temporary one called in a payload for something like a reboot. I hope that makes sense.
The shelly API is very decent but a little confusing at times. That is why your node is very attractive to me at least.
Many thanks again.

**Comment by windkh** [comment]
I am not sure if got your point. What do you mean with "auto on set" ??? 
The setting that controls how the switch should be set when powering up??? on, off, last mode?

**Comment by houser42** [comment]
Yes, @windkh  sorry for being unclear.
I am using the shelly relays in a purely off-grid scenario to save power via automations.
I would like to be able to do a remote 10 sec. reboot of one Shelly 1 PM plus that also has an "auto on in 8 hours"
setting for security purposes. A bit esoteric perhaps, but that is why I am here ;)

**Comment by windkh** [comment]
can you send me the json that is returned for http://yours-witch-ip-here/settings?
Just to see how you configured your shelly

**Comment by houser42** [comment]
I am not at the remote site now, so not sure I can get that information  for you
unless I can get it from the node red install, as I have remote access to that.
But there is nothing special with the Shelly 1PM Plus, apart from that it is, as I am sure you are aware
a Gen 2 device. Standard MQTT setup and other than that the only thingI have changed  is an 8 hour auto-on
which means it will always switch on after 8 hours.

**Comment by houser42** [comment]
Hello,
I just updated to your new 7.2.0 version that says it has support for changing the cofiguration
via payloads to the node. Does this help with my issues by any chance? 
The docs do not reflect this at this time, which is understandable. Juste very curious?
Many thanks!

**Comment by windkh** [comment]
Right now this is only implemented for gen1 devices…I will add support for gen2…soon

**Comment by houser42** [comment]
Great to hear! Thanks for your time and patience!

**Comment by houser42** [comment]
Just so I understand what the intended functionality is for this node in this regard?

Can we expect:
1.  to be able to have an auto-on timer always set on the relay that is,for example 8 hours.
2.  and also at the same time as that is set, be able to do a 10 sec reboot that overrides the auto-on timer?
Your node only preferred but any combination of node and MQTT payloads is ok.
This is the MQTT payload I am trying if that helps:
`var newMsg = 
{"topic":"shellyplus1pm-xxxxxx/rpc","payload":{"id":123, "src":"user_1", "method":"Switch.Set", "params":{"id":0,"on":false, "auto_on": true, "auto_on_delay":5}}}
return newMsg;
`
This switches of the Shelly, but does not come back on.
Grateful for a comment when you have a moment. Many thanks.

**Comment by windkh** [comment]
I reworked the rpc protocol for shelly gen 2 switch. Please have a look at the new example for shelly plus in version 8.0.0

**Comment by houser42** [comment]
Yes, this appears to be a great improvement and works pretty much as at least I had expected.

In my tests I am using the new 8.0 version of your node and the standard new 0.10.1 firmware on a Shelly 1PM plus that was also new.

1. Now, when first setting a timer on the device itself, in my case 8 hours
Sending the commands in your gen 2 example will override with a 2 sec toggle flip back on. This is great and is close to what I wanted.
With the 0.10.1 firmware on the Shelly it I also reflected in the webgui.

2. I prefer the discrete auto on, as the toggle command might accidentally turn the device off if one is not careful. 
This also works as expected after updating the Shelly to 0.10.1

Many thanks for this. You're a star!

**Comment by houser42** [comment]
Edit: One thing that could maybe be even better that is probably for the Shelly developers to look at rather than you: 
Should the webgui not updated by the Set Config payloads?

As it is now it is a little confusing:
1. If we set the Auto On timer in the webgui, it will count down in the web gui
regardless if the Shelly is switched off via the webgui or your node commands. 
like so:
<img width="353" alt="Screenshot 2022-03-31 at 09 25 02" src="https://user-images.githubusercontent.com/15192440/161005475-b92564a1-f887-44a3-a08b-da1f961a0bf4.png">

2. However, if the Auto On timer in the webgui is not set, it will still behave exactly the same with the payloads sent to your node, , but the webgui will not say anything about what is going on. Not ideal. But workable. Many thanks!

**Comment by houser42** [comment]
Hello,
If you would be so kind to have look at the attached flow some time when you have a moment I would really appreciate it.
This flow works but is a bit of a hack and I would appreciate a hint or two of how you would do this to optimise it
as your Shelly node is the master state in the flow, but it also needs to have two more switches wired in parallel, one for Home kit and one for the Node red dashboard. All serve to switch the Shelly the same way.
A physical moment switch at the shelly and the two soft switches should reflect a change anywhere between the three of them, yet not create a loop. I am unable to come up with a clean and robust solution. But again, this appears to work, so is perhaps a half-decent way to show why I am trying to do..

Can you suggest a cleaner and more robust way of doing this by any chance, optimised for your new Shelly node? 
Many thanks regardless!

`[
    {
        "id": "bd02da3896c29e8e",
        "type": "group",
        "z": "eef618ccc6e2ee8c",
        "name": "",
        "style": {
            "fill": "#c8e7a7",
            "label": true
        },
        "nodes": [
            "6cf1745b3ff6c936",
            "4af867cdef1fe329",
            "471bab8f3e6f3ee5",
            "2d525d44e40f0620",
            "7474a3430fe26c3b",
            "fc59cc75739f647e",
            "275e3477b122dccb",
            "d51fad32e4e06e01",
            "9d8303659e2b8c88",
            "1ba86a8a37c44aad",
            "4a56db0a0217c071",
            "bee423ae8e3b77bd",
            "ee6fb4a6d08475c3",
            "06ddbd6bdb128515",
            "1d06c797a0da1a3a",
            "9f7eb3b869ac7d8a",
            "24ffd3e970e86e62",
            "8347e45955618064",
            "56b25b4442efe183",
            "7724b8fa22901271"
        ],
        "x": 74,
        "y": 119,
        "w": 1192,
        "h": 522
    },
    {
        "id": "6cf1745b3ff6c936",
        "type": "homekit-service",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "isParent": true,
        "hostType": "0",
        "bridge": "1d2439381726168b",
        "accessoryId": "",
        "parentService": "",
        "name": "Switch 3 - Homekit",
        "serviceName": "Switch",
        "topic": "",
        "filter": false,
        "manufacturer": "NRCHKB",
        "model": "1.3.6",
        "serialNo": "Default Serial Number",
        "firmwareRev": "1.3.6",
        "hardwareRev": "1.3.6",
        "softwareRev": "1.3.6",
        "cameraConfigVideoProcessor": "ffmpeg",
        "cameraConfigSource": "",
        "cameraConfigStillImageSource": "",
        "cameraConfigMaxStreams": 2,
        "cameraConfigMaxWidth": 1280,
        "cameraConfigMaxHeight": 720,
        "cameraConfigMaxFPS": 10,
        "cameraConfigMaxBitrate": 300,
        "cameraConfigVideoCodec": "libx264",
        "cameraConfigAudioCodec": "libfdk_aac",
        "cameraConfigAudio": false,
        "cameraConfigPacketSize": 1316,
        "cameraConfigVerticalFlip": false,
        "cameraConfigHorizontalFlip": false,
        "cameraConfigMapVideo": "0:0",
        "cameraConfigMapAudio": "0:1",
        "cameraConfigVideoFilter": "scale=1280:720",
        "cameraConfigAdditionalCommandLine": "-tune zerolatency",
        "cameraConfigDebug": false,
        "cameraConfigSnapshotOutput": "disabled",
        "cameraConfigInterfaceName": "",
        "characteristicProperties": "{}",
        "waitForSetupMsg": false,
        "outputs": 2,
        "x": 810,
        "y": 440,
        "wires": [
            [
                "4af867cdef1fe329",
                "7474a3430fe26c3b",
                "8347e45955618064"
            ],
            []
        ]
    },
    {
        "id": "4af867cdef1fe329",
        "type": "ui_switch",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Switch 2 - NR Dash",
        "label": "Switch 2 - NR Dash",
        "tooltip": "",
        "group": "e48e8a33f9fc6cf2",
        "order": 1,
        "width": 7,
        "height": 1,
        "passthru": true,
        "decouple": "false",
        "topic": "payload",
        "topicType": "msg",
        "style": "",
        "onvalue": "{\"On\":true}",
        "onvalueType": "json",
        "onicon": "",
        "oncolor": "",
        "offvalue": "{\"On\":false}",
        "offvalueType": "json",
        "officon": "",
        "offcolor": "",
        "animate": true,
        "className": "",
        "x": 820,
        "y": 380,
        "wires": [
            [
                "6cf1745b3ff6c936",
                "56b25b4442efe183"
            ]
        ]
    },
    {
        "id": "471bab8f3e6f3ee5",
        "type": "shelly-gen2",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "hostname": "192.168.11.199",
        "description": "Switch 1 Shelly",
        "pollinginterval": 5000,
        "pollstatus": true,
        "getstatusoncommand": true,
        "devicetype": "Relay",
        "outputs": 1,
        "credentials": {
            "username": "",
            "password": ""
        },
        "x": 500,
        "y": 500,
        "wires": [
            [
                "275e3477b122dccb",
                "7724b8fa22901271"
            ]
        ]
    },
    {
        "id": "2d525d44e40f0620",
        "type": "switch",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "split",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "{\"On\":true}",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "{\"On\":false}",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 250,
        "y": 320,
        "wires": [
            [
                "9d8303659e2b8c88"
            ],
            [
                "4a56db0a0217c071"
            ]
        ]
    },
    {
        "id": "7474a3430fe26c3b",
        "type": "delay",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "",
        "pauseType": "rate",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "5",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": true,
        "allowrate": false,
        "outputs": 1,
        "x": 180,
        "y": 500,
        "wires": [
            [
                "fc59cc75739f647e"
            ]
        ]
    },
    {
        "id": "fc59cc75739f647e",
        "type": "json",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "",
        "property": "payload",
        "action": "",
        "pretty": false,
        "x": 250,
        "y": 360,
        "wires": [
            [
                "2d525d44e40f0620"
            ]
        ]
    },
    {
        "id": "275e3477b122dccb",
        "type": "json",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "",
        "property": "payload",
        "action": "",
        "pretty": false,
        "x": 770,
        "y": 220,
        "wires": [
            [
                "bee423ae8e3b77bd"
            ]
        ]
    },
    {
        "id": "d51fad32e4e06e01",
        "type": "inject",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Turn On",
        "props": [
            {
                "p": "payload",
                "v": "",
                "vt": "date"
            },
            {
                "p": "topic",
                "v": "",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 490,
        "y": 220,
        "wires": [
            [
                "9d8303659e2b8c88"
            ]
        ]
    },
    {
        "id": "9d8303659e2b8c88",
        "type": "function",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "0 on",
        "func": "msg.payload = {\n    method: \"Switch.Set\",\n    parameters : {\n        id : 0,\n        on : true,\n        // toggle_after : 2 // optional flip back time in seconds\n    }\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 260,
        "wires": [
            [
                "471bab8f3e6f3ee5"
            ]
        ]
    },
    {
        "id": "1ba86a8a37c44aad",
        "type": "inject",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Turn Off",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 490,
        "y": 300,
        "wires": [
            [
                "4a56db0a0217c071"
            ]
        ]
    },
    {
        "id": "4a56db0a0217c071",
        "type": "function",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "0 off",
        "func": "msg.payload = {\n    method: \"Switch.Set\",\n    parameters : {\n        id : 0,\n        on : false,\n        // toggle_after : 2 // optional flip back time in seconds\n    }\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 490,
        "y": 340,
        "wires": [
            [
                "471bab8f3e6f3ee5"
            ]
        ]
    },
    {
        "id": "bee423ae8e3b77bd",
        "type": "switch",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "cont",
                "v": "output\":true",
                "vt": "str"
            },
            {
                "t": "cont",
                "v": "output\":false",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 770,
        "y": 260,
        "wires": [
            [
                "ee6fb4a6d08475c3"
            ],
            [
                "06ddbd6bdb128515"
            ]
        ]
    },
    {
        "id": "ee6fb4a6d08475c3",
        "type": "ui_button",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "{\"On\":true}",
        "group": "e48e8a33f9fc6cf2",
        "order": 14,
        "width": 0,
        "height": 0,
        "passthru": true,
        "label": "{\"On\":true}",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "{\"On\":true}",
        "payloadType": "json",
        "topic": "topic",
        "topicType": "msg",
        "x": 790,
        "y": 300,
        "wires": [
            [
                "4af867cdef1fe329"
            ]
        ]
    },
    {
        "id": "06ddbd6bdb128515",
        "type": "ui_button",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "{\"On\":false}",
        "group": "e48e8a33f9fc6cf2",
        "order": 14,
        "width": 0,
        "height": 0,
        "passthru": true,
        "label": "{\"On\":false}",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "{\"On\":false}",
        "payloadType": "json",
        "topic": "topic",
        "topicType": "msg",
        "x": 790,
        "y": 340,
        "wires": [
            [
                "4af867cdef1fe329"
            ]
        ]
    },
    {
        "id": "1d06c797a0da1a3a",
        "type": "comment",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "3 switches in parallell. Each switch needs to be able to switch on and off and the other two switches need to reflect changes. All without creating a loop.",
        "info": "",
        "x": 630,
        "y": 160,
        "wires": []
    },
    {
        "id": "9f7eb3b869ac7d8a",
        "type": "comment",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "This Shelly is a physical relay that can also be switched with a physical button",
        "info": "",
        "x": 420,
        "y": 560,
        "wires": []
    },
    {
        "id": "24ffd3e970e86e62",
        "type": "comment",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "So the Shelly needs to be the master state",
        "info": "",
        "x": 440,
        "y": 600,
        "wires": []
    },
    {
        "id": "8347e45955618064",
        "type": "debug",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Switch 3 - Homekit",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1090,
        "y": 460,
        "wires": []
    },
    {
        "id": "56b25b4442efe183",
        "type": "debug",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Switch 2 - NR Dash",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1100,
        "y": 380,
        "wires": []
    },
    {
        "id": "7724b8fa22901271",
        "type": "debug",
        "z": "eef618ccc6e2ee8c",
        "g": "bd02da3896c29e8e",
        "name": "Switch 1 - Shelly Gen 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 1110,
        "y": 520,
        "wires": []
    },
    {
        "id": "1d2439381726168b",
        "type": "homekit-bridge",
        "bridgeName": "Dev share 1b",
        "pinCode": "033-96-068",
        "port": "",
        "advertiser": "bonjour-hap",
        "allowInsecureRequest": false,
        "manufacturer": "NRCHKB",
        "model": "1.4.3",
        "serialNo": "Default Serial Number",
        "firmwareRev": "1.4.3",
        "hardwareRev": "1.4.3",
        "softwareRev": "1.4.3",
        "customMdnsConfig": false,
        "mdnsMulticast": true,
        "mdnsInterface": "",
        "mdnsPort": "",
        "mdnsIp": "",
        "mdnsTtl": "",
        "mdnsLoopback": true,
        "mdnsReuseAddr": true,
        "allowMessagePassthrough": true
    },
    {
        "id": "e48e8a33f9fc6cf2",
        "type": "ui_group",
        "name": "Default",
        "tab": "3ecaa427cf920875",
        "order": 1,
        "disp": true,
        "width": "7",
        "collapse": true,
        "className": ""
    },
    {
        "id": "3ecaa427cf920875",
        "type": "ui_tab",
        "name": "Dev share",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]`
