### ISSUE TITLE
Shelly1 temperature addon

### ISSUE THREAD

**Issue by Guenni9** [windkh/node-red-contrib-shelly#62]
Dear friends, is it possible or planned to read out external temperatures?
I'm testing a Shelly 1PM with temperature addon and only get the internal temperature.
Thanks a lot!

**Comment by Guenni9** [comment]
Me again... let me clarify my question:
I'm looking for a way to inject the switching thresholds of the temperature automation in the Shelly with the temp.addon.
Reading out is no problem, I found it in ojects, sorry..
Tkanks, again!
![image](https://user-images.githubusercontent.com/101923813/159117116-489a67b1-8831-46cb-ae15-5cc7d6fe0aa8.png)

**Comment by windkh** [comment]
Ah ok… so you want to set the thresholds… l will try to implement it.

**Comment by windkh** [comment]
please check  the example settings.json in the example folder of version 7.2.0

**Comment by Guenni9** [comment]
Works fine! Just tested, Thank You!
