### ISSUE TITLE
After Update from 7.1.0 to 7.2.0 I see no sensor values

### ISSUE THREAD

**Issue by FrodoVDR** [windkh/node-red-contrib-shelly#63]
Since version 7.2.0 I can no longer see any sensor values.
I have checked this with the following devices:
Shelly EM, Shell 3EM and Shelly Plus 1PM.

**Comment by windkh** [comment]
Can you send me your flow?

**Comment by windkh** [comment]
Ah I found the problem: some devices return the values in a property meters and some in emeters.
7.3.0 should fix it

**Comment by windkh** [comment]
@FrodoVDR thanks for reporting, please test with 7.3.0
