### ISSUE TITLE
best way to split `node-red-contrib-shelly` payload based on output state ?

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#65]
Could you please have quick look at the attached flow of just a shelly and a split node to suggested best way to split `node-red-contrib-shelly` payload based on output state? Would really appreciate it. It should work the same for both the status output of the node it self and after an external change. I assume I should use `payload.switch0.output` ?
If so what should the lines in the split node be? String? Boolean? Many thanks for any feedback.

`[{"id":"5a16146eb8baceb4","type":"shelly-gen2","z":"59700accc10255c3","hostname":"192.168.58.99","description":"DEV 1 Plus PM","pollinginterval":5000,"pollstatus":true,"getstatusoncommand":true,"devicetype":"Relay","outputs":1,"credentials":{"username":"","password":""},"x":780,"y":640,"wires":[["1568840426ed62b0"]]},{"id":"1568840426ed62b0","type":"switch","z":"59700accc10255c3","name":"","property":"payload.switch0.output","propertyType":"msg","rules":[{"t":"eq","v":"true","vt":"str"},{"t":"eq","v":"false","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":950,"y":640,"wires":[["d3012e4c98664ac3"],["8bcef09bca9edf4a"]]},{"id":"d3012e4c98664ac3","type":"debug","z":"59700accc10255c3","name":"1","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1130,"y":620,"wires":[]},{"id":"8bcef09bca9edf4a","type":"debug","z":"59700accc10255c3","name":"2","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":1130,"y":660,"wires":[]}]`

**Comment by windkh** [comment]
I will have a look as soon as possible

**Comment by windkh** [comment]
Comparing a string is wrong. You should compare a boolean to true or false:

[{"id":"2c6bffe0d8827f5f","type":"shelly-gen2","z":"f45ce90b3151803b","hostname":"192.168.178.242","description":"","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":false,"devicetype":"Relay","outputs":1,"x":570,"y":440,"wires":[["1568840426ed62b0"]]},{"id":"1568840426ed62b0","type":"switch","z":"f45ce90b3151803b","name":"","property":"payload.switch0.output","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":770,"y":440,"wires":[["d3012e4c98664ac3"],["8bcef09bca9edf4a"]]},{"id":"d3012e4c98664ac3","type":"debug","z":"f45ce90b3151803b","name":"1","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":950,"y":420,"wires":[]},{"id":"8bcef09bca9edf4a","type":"debug","z":"f45ce90b3151803b","name":"2","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":950,"y":480,"wires":[]}]

**Comment by houser42** [comment]
Understood. That works much better than my solution!
Appreciate the help!
