### ISSUE TITLE
Shelly Pro4PM works fine ;-)

### ISSUE THREAD

**Issue by TheLion** [windkh/node-red-contrib-shelly#66]
Hi,

Querying the Shelly Pro4PM works just fine, but the debug shows `[shelly-gen2:7d485f0b.3348f] Shelly type mismatch: undefined`

I haven't tried switching power yet, as the device behind it is in use at the moment ;-)

**Comment by windkh** [comment]
Hi @TheLion 
yes it should work as the protocol is similar. However I can not test it as I do not own a Pro model.
If you could provide some info then I could make the changes here and send you the nodes for testing if you like.

**Comment by TheLion** [comment]
> Hi @TheLion yes it should work as the protocol is similar. However I can not test it as I do not own a Pro model. If you could provide some info then I could make the changes here and send you the nodes for testing if you like.

Sure. What would you like me to test?

**Comment by windkh** [comment]
@TheLion 
please call the following url from a browser window

`
http://192.168.178.242/shelly
`
Replace the IP address with your own please and let me know what was returned. Thanks in advance

**Comment by windkh** [comment]
Please try out 8.1.0 ... maybe it works already without any errors in this version.

**Comment by TheLion** [comment]
> @TheLion please call the following url from a browser window
> 
> `http://192.168.178.242/shelly` Replace the IP address with your own please and let me know what was returned. Thanks in advance

Sure. 

`{"name":"ShellyPro4PM","id":"shellypro4pm-84cca87eafec","mac":"84CCA87EAFEC","model":"SPSW-004PE16EU","gen":2,"fw_id":"20220330-150000/0.10.1-g8d603a2","ver":"0.10.1","app":"Pro4PM","auth_en":false,"auth_domain":null} `

**Comment by TheLion** [comment]
> Please try out 8.1.0 ... maybe it works already without any errors in this version.

Updated to 8.1.0 and error is gone!

Thanks!!
