### ISSUE TITLE
Shelly Switch Node kills Shelly (after a few days/weeks)

### ISSUE THREAD

**Issue by osulivanDE** [windkh/node-red-contrib-shelly#67]
Hello, it´s been a long path for me to come here but i am pretty sure the Switch node slowly "kills" Shelly Plug S Devices.

I have several of them around my house and some of them are connected to NR Flows and all of them experience a strange behavior which starts that the shellys become unresponsive for a few days and completely quit a few days after.

This is from the time one device started became unresponsive:
https://www.shelly-support.eu/index.php?attachment/30104-bildschirmfoto-2022-04-23-um-21-56-03-png

I am pretty sure the shelly Switch Node is responsible for this. Every Device i connect through the node "dies". I have to factory reset it and add it again to my network. If i point the node to an other Shelly, the other shelly "dies". 
Every other Shelly Plug S in my house does not have this problem (over one year without any trouble). The Node-Red connected Shellys only live from 5-30days until they die.

Maybe the node talks to often or in a strange way to the Shellys API and this leads to some kind of log overflow? I don´t know. Maybe this is some Shelly own Problem and only the shelly contrib node triggers this?

I´m gonna use Home Assistant functions to toggle the Shelly devices from now on. Maybe someone finds the cause of this problem.

Thanks

**Comment by windkh** [comment]
Hm this sounds strange. The nodes just talk to the device via the official API. Normally there is now way to damage a device via remote calls unless there is a bug in the internal shelly firmware. What polli deay do you use?
I for myself have several shellies connected for over a year without any problems.

i‘d like to reproduce your problem: please send me the flow.

**Comment by osulivanDE** [comment]
yeah, i also think this is a problem with the shelly firmware which in combination with the NR Switch causes this problem.

The polling interval is 5000ms (default)

`[{"id":"c4a59db25983393d","type":"function","z":"430f1c64ee6a14bf","name":"","func":"msg.ich= global.get(\"homeassistant.homeAssistant.states['person.ich'].state\");\nmsg.du= global.get(\"homeassistant.homeAssistant.states['person.du'].state\");\nmsg.TVshellystatus=global.get(\"homeassistant.homeAssistant.states['switch.wohnzimmer_tv'].state\");\n\n\nmsg.payload = {}\n\nif(msg.ich == \"ich\" || msg.du == \"du\")\n{\n    msg.payload = {\n    relay : 0,\n    on : true\n}\n}\nelse\n    msg.payload = {\n    relay : 0,\n    on : false\n}\n\n\n// XOR Damit das Shelly nur dann getriggert wird, wenn ein Statuswechsel überhaupt notwendig ist\nmsg.change = msg.TVshellystatus == \"on\" ^ msg.payload.on == true\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":120,"wires":[["7cc4380ec60a650e"]]}]`

**Comment by windkh** [comment]
Ok thanks and finally what firmware version do you have?

**Comment by osulivanDE** [comment]
Current version: 20220209-094058/v1.11.8-g8c7bb8d 
You have latest version on your device!

**Comment by windkh** [comment]
Ok hab ich auch hier. Wie merkst du dass er nicht mehr geht? Fehler in node-red oder schaltet er nicht mehr?

**Comment by osulivanDE** [comment]
Der Webserver der Shellys reagiert nicht mehr. Man kommt nicht mehr auf die HTTP Seite der Geräte und kann auch nichts mehr von außen an den Geräten triggern. Weder NR, noch Home Assistant, noch die Shelly Cloud App. Die einzigen Lebenszeichen der Geräte sehe ich im  Unifi Controller. Die Geräte sind im WLAN und senden ab dann massiv viele Daten im Vergleich zu den funktionierenden Geräten. (5MB innerhalb weniger Minuten, im Vergleich zu wenigen kb).

**Comment by windkh** [comment]
Wow… das klingt als würde der Amok laufen. 
Wie kann ich das provozieren? Soll ich an aus an aus … oder hängt grosse Last drann so dass er warm wird?

**Comment by osulivanDE** [comment]
Das wird leider schwierig das instant zu provozieren. Bei mir dauert das auch mal eine oder zwei Wochen, bis man etwas merkt.

Große Lasten hängen nicht dran. Einmal schalte ich nur eine Rohrbegleitheizung mit 30W, ein Shelly schaltet meinen Fernseher/Lautsprecher an/aus ca. 200W Last Peak.

Ich könnte mir vorstellen, dass das Shelly trotz debug:off dennoch irgendwelche Zugriffe loggt und da irgendwas volläuft.

Mein Flow sieht nur deswegen so "kompliziert" aus, weil ich früher dachte, ich tue dem Shelly einen Gefallen, wenn ich ihn nicht alle 10s triggere sondern nur dann, wenn  tatsächlich eine Statusänderung passieren soll aber die Rohrbegleitheizung hat seit fast 1 Monat nicht mehr schalten müssen, dennoch habe ich das Problem.

Achja, was mir aufgefallen ist (das hat aber vermutlich nichts direkt mit dem Thema zutun, ist aber auffällig):
Wenn ich im NR nachträglich die IP von der Node ändere, wird eine Fehlermeldung für die ehemalige (zuerst eingetragene Adresse ausgegeben, im Wechsel mit der neuen Adresse)

<img width="410" alt="Bildschirmfoto 2022-05-01 um 21 34 35" src="https://user-images.githubusercontent.com/44095221/166161812-0dc0ac04-8782-46dd-a51a-6574ff9a254d.png">

**Comment by windkh** [comment]
Ok dann probier ichs mal.
Kommt das bei anderen shellies auch vor?

**Comment by osulivanDE** [comment]
Die fehlerhafte Anzeige in NodeRed? 
Weder hinter der 2.50 noch der 2.31 hängt gerade ein Shelly. Ich habe das nur zum demonstrieren nachgebaut. 
Aufgefallen ist mir das als ich eines der Shellys resettet habe und das Ding eine neue IP bekommen hat und ich es im NR geändert habe. Dann habe ich gesehen, dass die alte IP immer noch angesprochen wird. Ich musste die Node löschen und neu anlegen mit der neuen IP, dann hatte ich ein ständiges "connected". 

Ich habe das Thema schonmal im Shelly Forum andiskutiert: https://www.shelly-support.eu/forum/index.php?thread/14724-shelly-plug-s-nach-ein-paar-wochen-betrieb-offline/&postID=153753#wcf69

**Comment by windkh** [comment]
Leg bitte für das zweite problem einen separaten issue an, dann kann ich das separat angehen.

**Comment by osulivanDE** [comment]
sehr gerne :)

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/166318682-761c0c03-c525-4d93-9dc4-5ccaf3017527.png)
Hier ist die Klammer und das else vertauscht

**Comment by windkh** [comment]
Ich hätte das kürzer geschrieben

let value = (msg.ich == "ich" || msg.du == "du");

msg.payload = {
    relay : 0,
    on : value
}


das sollte aber keinen Unterschied machen ob der shelly ein problem bekommt oder nicht.
Was im flow fehlt ist der shelly node selbst.

**Comment by osulivanDE** [comment]
Hey, Danke. Ja, ich bin super neu in JS.

**Comment by windkh** [comment]
@osulivanDE Zwichenstand: Mein ShellyPlug S läuft nun seit fast einer Woche problemlos mit Node-Red.

**Comment by osulivanDE** [comment]
Hi, lass den bitte nochmal etwas laufen. Das kann auch etwas dauern bis das das erste Mal auftaucht.
Ich kann inzwischen berichten, seitdem ich NR nicht mehr mit der Switch Node auf den Shelly lasse funktionieren meine beiden Shellys wieder tadellos.

**Comment by windkh** [comment]
Mein device läuft immer noch. Keine Probleme.

**Comment by windkh** [comment]
Meine Devices laufen schon seit Wochen ohne Probleme.
Soll ich den Issue schließen?

**Comment by osulivanDE** [comment]
Hi, danke fürs Testen. Schade nur, dass das Problem bei dir nicht aufgetreten ist.
Für mich hat sich jedenfalls das problematische Verhalten von allen Shellys gelöst die Node nicht mehr zu benutzen und dafür die Homeassistant eigene Funktion zu benutzen um die Shellys zu steuern.
Danke dir nochmal :)

**Comment by windkh** [comment]
Ich lasse die Tests weiter laufen. Falls ich was feststelle öffne ich diesen wieder.
