### ISSUE TITLE
wrong displayed IP adress in NR after changing IP

### ISSUE THREAD

**Issue by osulivanDE** [windkh/node-red-contrib-shelly#68]
a little strange behavior
if I change the IP Address of a "switch" node in NR afterwards, an error message is displayed for the former, at first entered address, alternating with the new address. Of course I deployed the change.

<img width="410" alt="Bildschirmfoto 2022-05-01 um 21 34 35" src="https://user-images.githubusercontent.com/44095221/166162455-046a9000-37b1-4761-a3c1-743b3d7ac76d.png">

you can see the former entered address is still showing up

**Comment by windkh** [comment]
what version do you use? I get a timeout error instead

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/166318022-b98cb76f-dc67-41c5-8733-0d3301c7926b.png)

**Comment by windkh** [comment]
I can not reproduce this even without network:

![image](https://user-images.githubusercontent.com/10910767/171052038-8e017db0-4525-4d19-99fe-19fb985ae90d.png)
