### ISSUE TITLE
Shelly I3 - Button Toggle mode

### ISSUE THREAD

**Issue by MrMennens-tech** [windkh/node-red-contrib-shelly#69]
When using the shelly I3 in Toggle mode i'm not able to get any output of the Device

**Comment by windkh** [comment]
I will check this

**Comment by windkh** [comment]
works with callback now. However it also worked using polling before.

**Comment by MrMennens-tech** [comment]
Weird... still not getting anything, probably doing something wrong i guess.....

![image](https://user-images.githubusercontent.com/90801376/188332393-f0ce28a1-c96a-4097-b0cb-8359d1632211.png)

`[{"id":"9efa042c.1ed728","type":"tab","label":"Test|_2","disabled":false,"info":""},{"id":"9faa1a16de438ea9","type":"shelly-gen1","z":"9efa042c.1ed728","hostname":"192.168.2.216","description":"I3 Hal","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":true,"devicetype":"Button","outputs":1,"rgbwmode":"color","x":410,"y":300,"wires":[["a84637192c4fe694","903bd102a901848e","dfbf422980a7d438"]]},{"id":"f0d05122a673f3d7","type":"inject","z":"9efa042c.1ed728","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":300,"wires":[["9faa1a16de438ea9"]]},{"id":"a11a51cc1f491e55","type":"debug","z":"9efa042c.1ed728","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1050,"y":320,"wires":[]},{"id":"6031b4dbfacdf4d8","type":"shelly-gen1","z":"9efa042c.1ed728","hostname":"192.168.2.159","description":"Dimmer Hal","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":true,"devicetype":"Dimmer","outputs":1,"x":830,"y":320,"wires":[["a11a51cc1f491e55"]]},{"id":"a84637192c4fe694","type":"function","z":"9efa042c.1ed728","name":"dim up, stop, down","func":"if(msg.payload.hookType === 'btn_on_url' && \n msg.payload.index === 0){\n msg.payload = {\n dim : 'up'\n }\n return [msg];\n} \n\nif(msg.payload.hookType === 'btn_on_url' && \n msg.payload.index === 1){\n msg.payload = {\n dim : 'stop'\n }\n return [msg];\n} \n\n\nif(msg.payload.hookType === 'btn_on_url' && \n msg.payload.index === 2){\n msg.payload = {\n dim : 'down'\n }\n return [msg];\n} \n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":630,"y":320,"wires":[["6031b4dbfacdf4d8"]]},{"id":"903bd102a901848e","type":"debug","z":"9efa042c.1ed728","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":590,"y":260,"wires":[]},{"id":"dfbf422980a7d438","type":"debug","z":"9efa042c.1ed728","name":"debug 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":580,"y":200,"wires":[]}]`

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/188333042-c35d9064-38bf-4e51-9867-20dd2d622252.png)
You must select the correct mode: callback should work with Version 9.13.0
