### ISSUE TITLE
Shelly Dimmer Cycle Up/Down

### ISSUE THREAD

**Issue by MrMennens-tech** [windkh/node-red-contrib-shelly#70]
Is it possible to cycle the dimming function up or down? (as with the URL actions)

- http://192.168.xxx.xxx/light/0?dim=up
- http://192.168.xxx.xxx/light/0?dim=down
- http://192.168.xxx.xxx/light/0?dim=stop

**Comment by windkh** [comment]
Right now not, but if you need it I can implement it

**Comment by MrMennens-tech** [comment]
Would be nice, I'm looking to control the dimmer with a Shelly i3 switch

**Comment by windkh** [comment]
can you please try something like that with the latest version?

if(msg.payload.hookType === 'btn_on_url' && 
    msg.payload.index === 0){
    msg.payload = {
        dim : 'up'
    }
    return [msg];
} 

if(msg.payload.hookType === 'btn_on_url' && 
    msg.payload.index === 1){
    msg.payload = {
        dim : 'stop'
    }
    return [msg];
} 


if(msg.payload.hookType === 'btn_on_url' && 
    msg.payload.index === 2){
    msg.payload = {
        dim : 'down'
    }
    return [msg];
} 

![image](https://user-images.githubusercontent.com/10910767/188331517-9e7ef37a-eef9-406f-a0ca-a1a3c747e7f4.png)

**Comment by windkh** [comment]
[{"id":"c6cd9516e2685034","type":"shelly-gen1","z":"62a53d6e4cbdfb9a","hostname":"192.168.178.231","description":"I3","mode":"callback","server":"033a6e9acf499057","outputmode":"event","uploadretryinterval":"5000","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":true,"devicetype":"Button","outputs":1,"rgbwmode":"color","x":290,"y":540,"wires":[["70669bf98cb5fc44","d156c16ef1f5945b"]]},{"id":"e83b39c806e7e328","type":"inject","z":"62a53d6e4cbdfb9a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":540,"wires":[["c6cd9516e2685034"]]},{"id":"a9a4cecf.d695d","type":"debug","z":"62a53d6e4cbdfb9a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":850,"y":560,"wires":[]},{"id":"55d2b0645b79d96e","type":"shelly-gen1","z":"62a53d6e4cbdfb9a","hostname":"192.168.178.247","description":"Dimmer","mode":"none","server":"033a6e9acf499057","uploadretryinterval":"5000","pollinginterval":5000,"pollstatus":false,"getstatusoncommand":true,"devicetype":"Dimmer","outputs":1,"credentials":{},"x":700,"y":560,"wires":[["a9a4cecf.d695d"]]},{"id":"70669bf98cb5fc44","type":"function","z":"62a53d6e4cbdfb9a","name":"dim up, stop, down","func":"if(msg.payload.hookType === 'btn_on_url' && \n    msg.payload.index === 0){\n    msg.payload = {\n        dim : 'up'\n    }\n    return [msg];\n} \n\nif(msg.payload.hookType === 'btn_on_url' && \n    msg.payload.index === 1){\n    msg.payload = {\n        dim : 'stop'\n    }\n    return [msg];\n} \n\n\nif(msg.payload.hookType === 'btn_on_url' && \n    msg.payload.index === 2){\n    msg.payload = {\n        dim : 'down'\n    }\n    return [msg];\n} \n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":510,"y":560,"wires":[["55d2b0645b79d96e"]]},{"id":"d156c16ef1f5945b","type":"debug","z":"62a53d6e4cbdfb9a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":470,"y":500,"wires":[]},{"id":"033a6e9acf499057","type":"shelly-gen1-server","port":"20001","hostname":""}]

**Comment by windkh** [comment]
@MrMennens-tech  I do not have a dimmer at hand, but something like that should work

**Comment by windkh** [comment]
@MrMennens-tech  please report back if it works and then I can create an example flow.
I will close this issue in the meantime.

Sorry that you had to wait so long, but I was quite busy the last months.

**Comment by MrMennens-tech** [comment]
No worries, but as said on the other issue, I'm unable to get any ouput when pressing the buttons.
So i'm not able to test the rest...
