### ISSUE TITLE
Is it possible to use shelly h&t with this node?

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#71]
Question is the title: Is it possible to use shelly h&t with this node?
Will the node send the temp and humidity values without need for mqtt?
Many thanks.

**Comment by windkh** [comment]
I think so. I will add an item in the combobox of the config node where you can select it

**Comment by windkh** [comment]
I ordered new the H&T gen2 device: will implement both soon.

**Comment by windkh** [comment]
Note: gen 1 and gen 2 devices only support webhooks (no scripts)

**Comment by windkh** [comment]
With the next release shelly plus H&T will be supported.
