### ISSUE TITLE
timeouts block Node-RED

### ISSUE THREAD

**Issue by micdis** [windkh/node-red-contrib-shelly#72]
Hi!
with setting up my HA on an Odroid newly I do get a lot of lagging through these messages in die Node-RED Log:

`[shelly-gen1:2abe5d25a74a25e8] timeout of 5000ms exceeded`

I'm not sure why this does happen, but out of Node-RED the shelly work normally and responsive.
Am I alone with this issue?

**Comment by charlesparvin** [comment]
I'm having a few issues with timeouts on my shelly flows as well that make some actions (using it to open/close shutters) get skipped 

I haven't been able to figure out what is causing one shelly module to trigger, the next one to fail and the following one to work fine.

**Comment by windkh** [comment]
Can you describe the scenario for me… maybe I can reproduce it somehow

**Comment by charlesparvin** [comment]
My issue is probably impossible to replicate at demande, I have 12 shelly nodes for my rollers, and a few different flows to open and close them at given times of the day. 

Randomly one will show a timeout message in the log and skip the action. NodeRED's "catch" node doesn't seem to catch it either.

Wi-Fi shouldn't be an issue either, the router is at the center of the house and the signal is pretty strong everywhere inside the house apparently.

Maybe a setting to retry X times timed out actions would be enough for >99% these failures? But it still wouldn't fix micdis' issue with the lack of responsiveness

**Comment by windkh** [comment]
do you use several nodes with the same IP address?

**Comment by houser42** [comment]
Not sure if this q was for me, but I'll answer anyway.

Yes, I have used several nodes with same IP but different ID.s when testing Shelly Pro 4.
My timing issues which were identical to this thread went away when I redid the dhcp by allowing my router to set the ip adress for the shellies and then set the IP to static also on the shellies for added robustness. 
So I assumed the shellies were experiencing a conflict with IP delegation. Ah well. FWIW.

**Comment by micdis** [comment]
thanks for all the answers and ideas, I will try out DHCP and static IP changing and will call back. Thanks!

**Comment by charlesparvin** [comment]
On my currently zero-issue setup I have shelly nodes in link-in link-out paths (and using link call to send my open/close queries) and all shelly nodes have a "static" IP assigned by the DHCP server (by reserving an IP address for each of their MAC adresses)

**Comment by windkh** [comment]
I have a new theory: maybe the shelly can only a certain amount of calls per second.

**Comment by windkh** [comment]
Short question: the timeouts are normal behavior if you use window or door sensors that sleep all the time and would only wake up if the door is opened or closed.

To the ones that have those timeouts: what type of shelly do you use?

**Comment by houser42** [comment]
> To the ones that have those timeouts: what type of shelly do you use?
Just clarifying, as I posted here on this a while back:
I use 6-7 different types of Shellies. Used to have timing issues in some installs but they were
resolved as probable IP/DHCP issues.
All good now in that regards and no timing issues that I am aware of. FWIW.

**Comment by windkh** [comment]
@houser42 ok good!
@micdis what about you?
@charlesparvin what about you?

**Comment by windkh** [comment]
@micdis what about you?
@charlesparvin what about you?

**Comment by windkh** [comment]
@micdis @charlesparvin can you please try out the new callback mode?

**Comment by micdis** [comment]
hi there! My problem actually went away without me recon what changed. :- ) 
The shelly-timeouts are gone.

**Comment by windkh** [comment]
Ok nice

**Comment by charlesparvin** [comment]
Sorry I had missed the ping. I also haven't seen any unexplainable timeouts in the last weeks or months!
