### ISSUE TITLE
First test with Shelly 4 Pro PM

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#73]
Hello,

I have this node working reliably with all many different shelly devices with no issues.
Working on my first install with a Shelly 4 Pro PM.
I am so far getting time-out issues when using more than the first channel.
What is best practice for using this 4 channel relay if you have a minute please?

Again, it is all working, but the Shelly 4 Pro PM hangs and gives a:
"Error: timeout of 5000ms exceeded" whenever I use more than one channel.
Works again after a while.

I assume simply one node per channel and change the id?
I have tried just using one node and using link nodes, but that gives the same result so far.
Not sure what to look for. Can you comment? Many thanks.

**Comment by windkh** [comment]
Can you send me the flow so that I can see what you are doing?

**Comment by houser42** [comment]
> Can you send me the flow so that I can see what you are doing?

Sure. Is this a good way of using your node for the Shelly 4 Pro PM.
If not, please suggest best practice in your opinion?

Many thanks

`[
    {
        "id": "bf0b2b5bc3099342",
        "type": "inject",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "ON",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1750,
        "y": 880,
        "wires": [
            [
                "64057a0533e7d16c"
            ]
        ]
    },
    {
        "id": "4c688dfe27435efc",
        "type": "inject",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "OFF",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1750,
        "y": 920,
        "wires": [
            [
                "ea37801a7e280916"
            ]
        ]
    },
    {
        "id": "0ce21be72ba99c3c",
        "type": "ui_switch",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "Channel 4",
        "label": "Channel 4",
        "tooltip": "",
        "group": "54c4ddb436178d2b",
        "order": 2,
        "width": 6,
        "height": 1,
        "passthru": false,
        "decouple": "false",
        "topic": "",
        "topicType": "str",
        "style": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "onicon": "",
        "oncolor": "",
        "offvalue": "false",
        "offvalueType": "bool",
        "officon": "",
        "offcolor": "",
        "animate": true,
        "className": "",
        "x": 1930,
        "y": 1180,
        "wires": [
            [
                "249dd3892a6818fd"
            ]
        ]
    },
    {
        "id": "e5074ea88fcc6f47",
        "type": "shelly-gen2",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "hostname": "192.168.11.31",
        "description": "220 SH dev 1",
        "pollinginterval": 5000,
        "pollstatus": true,
        "getstatusoncommand": true,
        "devicetype": "Relay",
        "outputs": 1,
        "x": 1700,
        "y": 1080,
        "wires": [
            [
                "fc49493cbf0636c3"
            ]
        ]
    },
    {
        "id": "64057a0533e7d16c",
        "type": "function",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "Shelly api gen 2 on",
        "func": "msg.payload = {\n    method: \"Switch.Set\",\n    parameters: {\n        id: 3,\n        on: true\n    }\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1720,
        "y": 1000,
        "wires": [
            [
                "e5074ea88fcc6f47"
            ]
        ]
    },
    {
        "id": "ea37801a7e280916",
        "type": "function",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "Shelly api gen 2 off",
        "func": "msg.payload = {\n    method: \"Switch.Set\",\n    parameters: {\n        id: 3,\n        on: false\n    }\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1720,
        "y": 1040,
        "wires": [
            [
                "e5074ea88fcc6f47"
            ]
        ]
    },
    {
        "id": "152d7e5ca22f039d",
        "type": "switch",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "switch boolean",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 1680,
        "y": 1180,
        "wires": [
            [
                "0ce21be72ba99c3c"
            ],
            [
                "0ce21be72ba99c3c"
            ]
        ]
    },
    {
        "id": "fc49493cbf0636c3",
        "type": "change",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "",
        "rules": [
            {
                "t": "delete",
                "p": "payload",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status.ble",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status.cloud",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"input:0\"]",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status.mqtt",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status.sys",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status.wifi",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].source",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].apower",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].voltage",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].current",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].aenergy",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "status[\"switch:0\"].temperature",
                "pt": "msg"
            },
            {
                "t": "move",
                "p": "status[\"switch:0\"].output",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1690,
        "y": 1140,
        "wires": [
            [
                "152d7e5ca22f039d"
            ]
        ]
    },
    {
        "id": "249dd3892a6818fd",
        "type": "switch",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "switch boolean",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 1460,
        "y": 1000,
        "wires": [
            [
                "64057a0533e7d16c"
            ],
            [
                "ea37801a7e280916"
            ]
        ]
    },
    {
        "id": "72df73d6c3c52d90",
        "type": "comment",
        "z": "a9870257c147ed72",
        "g": "59f137165546033f",
        "name": "channel 4",
        "info": "",
        "x": 1440,
        "y": 880,
        "wires": []
    },
    {
        "id": "54c4ddb436178d2b",
        "type": "ui_group",
        "name": "Dev 1",
        "tab": "66a5096fe286880f",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false,
        "className": ""
    },
    {
        "id": "66a5096fe286880f",
        "type": "ui_tab",
        "name": "Home",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]`

**Comment by windkh** [comment]
I always prefer the function node as it is more compact

[{"id":"bf0b2b5bc3099342","type":"inject","z":"ae7fbfe54b43d76a","name":"ON","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":490,"y":140,"wires":[["64057a0533e7d16c"]]},{"id":"4c688dfe27435efc","type":"inject","z":"ae7fbfe54b43d76a","name":"OFF","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":490,"y":180,"wires":[["ea37801a7e280916"]]},{"id":"0ce21be72ba99c3c","type":"ui_switch","z":"ae7fbfe54b43d76a","name":"Channel 4","label":"Channel 1","tooltip":"","group":"54c4ddb436178d2b","order":2,"width":6,"height":1,"passthru":false,"decouple":"false","topic":"","topicType":"str","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","animate":true,"className":"","x":790,"y":340,"wires":[["249dd3892a6818fd"]]},{"id":"e5074ea88fcc6f47","type":"shelly-gen2","z":"ae7fbfe54b43d76a","hostname":"192.168.178.242","description":"220 SH dev 1","mode":"polling","server":"04263f2d054cc2a1","uploadretryinterval":"5000","pollinginterval":"3000","pollstatus":true,"getstatusoncommand":true,"devicetype":"Relay","outputs":1,"x":440,"y":340,"wires":[["c0d891b674f724bf"]]},{"id":"64057a0533e7d16c","type":"function","z":"ae7fbfe54b43d76a","name":"Shelly api gen 2 on","func":"msg.payload = {\n method: \"Switch.Set\",\n parameters: {\n id: 0,\n on: true\n }\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":460,"y":260,"wires":[["e5074ea88fcc6f47"]]},{"id":"ea37801a7e280916","type":"function","z":"ae7fbfe54b43d76a","name":"Shelly api gen 2 off","func":"msg.payload = {\n method: \"Switch.Set\",\n parameters: {\n id: 0,\n on: false\n }\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":460,"y":300,"wires":[["e5074ea88fcc6f47"]]},{"id":"249dd3892a6818fd","type":"switch","z":"ae7fbfe54b43d76a","name":"switch boolean","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":200,"y":260,"wires":[["64057a0533e7d16c"],["ea37801a7e280916"]]},{"id":"72df73d6c3c52d90","type":"comment","z":"ae7fbfe54b43d76a","name":"channel 1","info":"","x":180,"y":140,"wires":[]},{"id":"c0d891b674f724bf","type":"function","z":"ae7fbfe54b43d76a","name":"switch0","func":"var on = msg.payload[\"switch0\"].output;\nmsg.payload = on;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":620,"y":340,"wires":[["0ce21be72ba99c3c"]]},{"id":"54c4ddb436178d2b","type":"ui_group","name":"Dev 1","tab":"66a5096fe286880f","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"04263f2d054cc2a1","type":"shelly-gen2-server","port":"10001"},{"id":"66a5096fe286880f","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
