### ISSUE TITLE
9.0 version does not react to payload with gen 2?

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#74]
Hello,

I updated to 9.0 today as it is a calm week.
It seems the node is now unresponsive for payloads for gen 2 devices?
HAs something changed with regards to the API or other? I see nothing new in the docs?
I am using simple polling and not the new server functionality.
I see nothing in debug, but a generic message pops up in the general debug flow:
`TypeError: Cannot read property 'addListener' of null`

Grateful for a comment.

**Comment by windkh** [comment]
ah ok that should not be... I will check asap

**Comment by windkh** [comment]
can you send me a flow or tell me at least what gen 2 device you are using?

**Comment by houser42** [comment]
Only tested with a Shelly 1PM plus so far. Travelling so can not send flow now..

**Comment by windkh** [comment]
ok thanks I will try to reproduce it

**Comment by windkh** [comment]
should be fixed in 9.1.0 thanks for reporting
