### ISSUE TITLE
Plus 1PM - no status output if switched via web interace

### ISSUE THREAD

**Issue by S474N** [windkh/node-red-contrib-shelly#77]
Nodered + plugin set correctly with enabled status output:
![image](https://user-images.githubusercontent.com/16512337/175777735-cf0136de-2436-41b0-a92f-c015243f9e54.png)

But if the Shelly is turned on/off via webinterface, there isn't information in NR flow, but directly in mqtt this information is send.
![image](https://user-images.githubusercontent.com/16512337/175777788-b8f65180-8ddc-4c36-adf3-995543230a25.png)

**Comment by windkh** [comment]
This check box means that you get an output whenever you send a command to the node. It has nothing to do with the webinterface

**Comment by S474N** [comment]
OK, and how can i obtain information, if the Shelly will be toggled via web interface or wall switch?

**Comment by windkh** [comment]
It sends you the status cyclically… in your case every 5s.Gesendet mit der WEB.DE iPad AppAm 25.06.22 um 20:07 schrieb S474N
                
            
            
                
                    Von: "S474N" ***@***.***>Datum: 25. Juni 2022An: "windkh/node-red-contrib-shelly" ***@***.***>Cc: "Comment" ***@***.***>,"Karl-Heinz Wind" ***@***.***>Betreff: Re: [windkh/node-red-contrib-shelly] Plus 1PM - no status output if switched via web interace (Issue #77)
                
                
OK, and how can i obtain information, if the Shelly will be toggled via web interface or wall switch?

**Comment by S474N** [comment]
OK, but via mqtt is status send immediately.

**Comment by windkh** [comment]
Try callback mode then
