### ISSUE TITLE
GEN2 enabled Authentication fails

### ISSUE THREAD

**Issue by aschmidt74** [windkh/node-red-contrib-shelly#79]
I'm running a few gen2 `Shelly Plus 2 pm` devices, in `shutter`-mode or `switch`-mode respecticely.
In node-red the gen2-nodes work fine in `callback`-mode, all scripts get pushed nicely and callback correctly.

_However_ as soon as I **enable Authenticaion** in a device, update the node with credentials (`"admin"`/`<password>` alternatively `<empty>`/`<password>`) and redeploy,
I get this as the gen2-nodes output: `Uploading script failed Error: Request failed with status code 401`

`Upload Retry Interval=0` even led to node-red **restart loop**.

**Comment by windkh** [comment]
Thanks for reporting this... I will check this

**Comment by windkh** [comment]
It seems that the gen 2 devices only have a password and basic auth is replaced with digest auth.

**Comment by aschmidt74** [comment]
very true.
**basic-auth** doesn't work anymore.❌
only **digest-auth** is supported.✅

**Comment by windkh** [comment]
@windkh 
https://stackoverflow.com/questions/54842977/digest-auth-using-axios
https://axios-digest-auth.mhoc.co/

**Comment by windkh** [comment]
Digest auth should work now, but not 100%. I found out that SetConfig refuses  the authorization while all other routes that I tested work flawlessly. Right now only polling mode works fine with authorization enabled.
