### ISSUE TITLE
"Shelly type mismatch: SNSW-001X16EU"

### ISSUE THREAD

**Issue by hjojohan** [windkh/node-red-contrib-shelly#80]
![121](https://user-images.githubusercontent.com/6337514/185443755-ffa6e309-1cb7-4f73-81c5-c937fcea1c45.jpg)

Hi I get this message '"Shelly type mismatch: SNSW-001X16EU" ' and '"Request failed with status code 404 'in NodeRed debug window. The relay toogle on/off as expected,  what iss wrong.. latest fw installed in the relay Shelley1 Plus

**Comment by hjojohan** [comment]
ping, any clue what i am doing wrong or is it a unsopported relay ?

**Comment by windkh** [comment]
Sry I am still on vacation

**Comment by windkh** [comment]
What device did you choose??

**Comment by windkh** [comment]
Show me your config node

**Comment by hjojohan** [comment]
![image](https://user-images.githubusercontent.com/6337514/185804038-f76e91e3-c3c5-49b0-8ad5-d6659349bd3f.png)

**Comment by hjojohan** [comment]
![image](https://user-images.githubusercontent.com/6337514/185804059-01159125-f7f4-4ed0-8433-1032343ab2c2.png)

**Comment by hjojohan** [comment]
![image](https://user-images.githubusercontent.com/6337514/185804118-5b580b9d-105c-4961-b1b9-a81556ba574e.png)

**Comment by hjojohan** [comment]
![image](https://user-images.githubusercontent.com/6337514/185804179-f859cf37-1fbb-4276-844f-618a306253c4.png)

**Comment by windkh** [comment]
You should use the 2nd generation node not the old one

**Comment by hjojohan** [comment]
I have changed to 2nd version and now the relay is silent, the switch dont toggle anymore

**Comment by hjojohan** [comment]
![image](https://user-images.githubusercontent.com/6337514/185804270-f26aac6f-0a53-43b4-ad08-5be9670e85a7.png)

**Comment by hjojohan** [comment]
ok i did this, now its working 

msg.payload = 
{
    method: 'Switch.Set',
	parameters: {
        id: 0,
        on: true,
        toggle_after: 1 // optional flip back time in seconds
    }
}


return msg;

**Comment by windkh** [comment]
Ok good
