### ISSUE TITLE
"Shelly type mismatch: SHSW-21"

### ISSUE THREAD

**Issue by eSoCGN** [windkh/node-red-contrib-shelly#81]
I've got gen1 shellies for my roller shutters. They work quite well with the setting "Roller - Shelly 2, 2.5".
But... I've got plenty of messages "Shelly type mismatch: SHSW-21" from each Shelly
In debug it says: 
```
<timestamp> node: <shellyXXX>
msg : string[29]
"Shelly type mismatch: SHSW-21"
```

How can I filter these? My usual filter stragegy ... if (msg.payload == "blabla") doen't fit at all. 
And, more important, why does node red throw an error when all is working well?

Kind regards and thanks for your great work
 Eric

**Comment by windkh** [comment]
You have chosen the wrong device type from the list.

Is it a second generation device?

**Comment by windkh** [comment]
see https://github.com/windkh/node-red-contrib-shelly/issues/80

**Comment by eSoCGN** [comment]
Hi,
I don't think it's the wrong type ... it all works well in "Roller - Shelly 2, 2.5" mode. 
It's an "old" Shelly2 in roller mode. No "plus" nor "pro" model.
The request http://IPadress/shelly displays the the following:
{"type":"SHSW-21","mac":"807D3A5B28B8","auth":false,"fw":"20220809-123410/v1.12-g99f7e0b","discoverable":false,"num_outputs":2, "num_meters":1, "num_rollers":1}

**Comment by windkh** [comment]
Hm maybe it is a new device type. I will add it, thanks for your input

**Comment by eSoCGN** [comment]
Kein Problem, lass mich wissen wenn ich helfen kann.
VG
