### ISSUE TITLE
Shelly Gen 2 device with 0.11.0-beta3 firmware results in "Shelly type mismatch" error

### ISSUE THREAD

**Issue by chultquist** [windkh/node-red-contrib-shelly#82]
Hi,

I recently had to update the firmware on my Plus1 PM device to deal with a known issue where it was incorrectly warning about over-voltage conditions. After doing this, I'm unable to connect to the device in Node Red. Here is what I get when I query the /shelly endpoint on the device:

`{"name":null,"id":"shellyplus1pm-a8032abadd1c","mac":"A8032ABADD1C","gen":2,"fw_id":"20220812-132933/0.11.0-beta3-gfc37777","ver":"0.11.0-beta3","app":"Plus1PM","auth_en":false,"auth_domain":null}`

It looks like the "model" key is missing (but there is an "app" which may be the same thing). I'm not sure whether this is a bug in the beta firmware, or possibly a change that we'll need to adapt to once this firmware becomes official.

Thanks,

Carl

**Comment by windkh** [comment]
Thanks for reporting. Hm this looks strange. I will try the same with one of my devices here. 
Maybe I need to remove this check in future. However it us the only thing I can do to prevent wrong configurations.

**Comment by windkh** [comment]
0.11.0-beta1 still contains the model property. The app was already there.

![image](https://user-images.githubusercontent.com/10910767/188119978-9ab701f7-fd37-4278-aa30-b119ea87a352.png)

**Comment by chultquist** [comment]
Interesting. So perhaps if I update the firmware to that specific version then I should be sorted. Let me see if I can do that...

**Comment by windkh** [comment]
Hm I downgraded to the official one 0.10.3 and now I can not install any beta again...

**Comment by chultquist** [comment]
Yes, me too...

**Comment by windkh** [comment]
@chultquist  I will close the issue for now. Please reopen it if it occurs again. Thanks for reporting!
