### ISSUE TITLE
Shelly 2.2 invalid number

### ISSUE THREAD

**Issue by rallep71** [windkh/node-red-contrib-shelly#87]
Shelly 2.5 invalid number since the last updates, the functions all work. see pictures.

![shelly25](https://user-images.githubusercontent.com/2786491/188297342-5be8bfcc-1866-44e5-a243-c30e43971ede.png)
![shelly251](https://user-images.githubusercontent.com/2786491/188297347-aed529dd-0e67-428e-8f97-3bca93dca9c7.png)

thx

**Comment by windkh** [comment]
Thanks for reporting?
I guess it us a unused propery in the callback mode. 
Enable callback, add a balue in the red field, change mode back to none.

**Comment by rallep71** [comment]
thanks for the help, it works now. You have to know that first! :D

**Comment by windkh** [comment]
I added something in the code to avoid this in future, thanks, should be fixed in  next version
