### ISSUE TITLE
'unkown shelly-gen1' when using 'shelly TRV flow'

### ISSUE THREAD

**Issue by klkl140** [windkh/node-red-contrib-shelly#89]
There seems to be a small error in the 'shelly TRV flow' example flow.
I have node-red-contrib-shelly 1.10.1 installed

**Comment by windkh** [comment]
Ok I will hava a look

**Comment by klkl140** [comment]
Thanks for your work, ... but I still get the same error
<img width="238" alt="Bildschirmfoto 2022-09-17 um 08 48 18" src="https://user-images.githubusercontent.com/8624766/190844483-1801e674-2ea0-4c53-904f-dc2ba4594490.png">

**Comment by windkh** [comment]
You need to install shelly 9.15.

**Comment by klkl140** [comment]
Thanks again.
Sorry, but I need another kick. My node-red palette shows node-red-contrib-tasmota as 0.9.12 being actual.
Then i downloaded 0.9.15.tar.gz from https://github.com/windkh/node-red-contrib-shelly/releases/tag/V9.15.0
renamed it to .tgz and tried to install it in node-red using the ‚upload Module tgz-Datei‘ button.
This gives the attached error message with an empty protocol.
What am i doing wrong (and how can I do it in the right way :-) ?

Greetings Klaus

**Comment by windkh** [comment]
Tasmota?
Just install it from the side bar in node-red: palette verwalten

**Comment by klkl140** [comment]
That was it. Lost in too many open projects :-) Thanks again.
