### ISSUE TITLE
Shelly1 addon sensor

### ISSUE THREAD

**Issue by bizzottogary** [windkh/node-red-contrib-shelly#90]
How to read on Shelly1 the external temperature sensors?

**Comment by windkh** [comment]
There should be a property in the status if available

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/193898883-831c9b18-399b-4be9-ae6f-2e87e278d6a3.png)

**Comment by asyvan** [comment]
That is the internal temperature sensor of Shelly.
The Shelly 1/1PM can have external temperature sensors (up to 3) using the Shelly Addon.

**Comment by bizzottogary** [comment]
Yes I know, my Shelly 1 have a external sensors connected. I can see these
sensors on Shelly app but not on Node Red

Il sab 26 nov 2022, 19:06 asyvan ***@***.***> ha scritto:

**Comment by windkh** [comment]
@bizzottogary 
The external sensors can be read from msg.status.ext_temperature["0"].tC
see also 
https://github.com/windkh/node-red-contrib-shelly/issues/104#issuecomment-1328092021

**Comment by bizzottogary** [comment]
I don't find "msg.status.ext_temperature["0"].tC"

![Screenshot1](https://user-images.githubusercontent.com/52651545/204366505-ac2d6a8f-2f97-4531-ab0e-83eae461bc4b.PNG)
![Screenshot2](https://user-images.githubusercontent.com/52651545/204366516-53fcc28f-08ce-4f30-9d66-2fa237145da8.PNG)
![Screenshot3](https://user-images.githubusercontent.com/52651545/204366547-1f07d678-9611-44a4-909f-cedbf231daa6.PNG)
![Screenshot4](https://user-images.githubusercontent.com/52651545/204366591-5e79158c-58a8-4346-a083-0658ed10a873.PNG)
![Screenshot5](https://user-images.githubusercontent.com/52651545/204366967-2ee1e46c-e797-422b-b1e9-d5b9ae5a33fb.PNG)

**Comment by asyvan** [comment]
> I don't find "msg.status.ext_temperature["0"].tC"
> 

It’s not in msg.payload. 
It’s under msg.status. 

Set your debug node to display entire object and not just msg.payload. 

One improvement this Shelly node could do would to lift this into msg.payload.

**Comment by bizzottogary** [comment]
Thanks @asyvan I find it
