### ISSUE TITLE
Shelly 1L: cannot get the output status of relays after every interaction  

### ISSUE THREAD

**Issue by brunialti** [windkh/node-red-contrib-shelly#94]
I have a Shelly 1L that works correctly in NR3, that is I can switch it on/off in the flows. I also checked the " Enable status output after each command" box but I do not get the status after any interaction thru NR3 as expected.

EDIT: to be more explicative: I sometime get the status after some seconds ( 5-10 secs) sometimes i do not. I expected to get reliably status within a reasonable time windows.

**Comment by windkh** [comment]
Hi @brunialti 
I just tested it with a plug-s and here it worked

![image](https://user-images.githubusercontent.com/10910767/194777125-a2588a0d-0fb2-4aed-b727-1891f89ee958.png)

So I have no idea where the difference should be between that one and the Shelly 1L.

Do you get any errors in the console or in the debug side bar?

**Comment by brunialti** [comment]
Thank you for your fast answer. It seems my problem is erratic. I'll made more tests. If it has to work we'll make it work !

**Comment by brunialti** [comment]
btw: how can I detect/discriminate  when the relay is activated by a physical push button vs NR command?

**Comment by windkh** [comment]
Hm büno idea. Have a look at msg.status ... if you can find the inputs there, then you can use that info
