### ISSUE TITLE
Shelly type mismatch: SHPLG2-1 ?

### ISSUE THREAD

**Issue by rallep71** [windkh/node-red-contrib-shelly#95]
Hallo,

Node Red zeigt mir folgenden Fehler seit dem letzten Update auf 10.1.0: "Shelly type mismatch: SHPLG2-1'

Folgendes Produkt verwende ich: https://www.amazon.de/gp/product/B0835YG5HK/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

![shelyplug2](https://user-images.githubusercontent.com/2786491/194924123-564b5488-2ef3-438d-b945-ebc571756507.png)

![shplu](https://user-images.githubusercontent.com/2786491/194924138-cf948647-3a60-489c-b47d-a6622f7666db.png)

Thx

**Comment by windkh** [comment]
Ah ok den habe ich noch nicht.
Als was hast den angelegt?
Gen1 Relais?

**Comment by rallep71** [comment]
Habe zwei Bilder hinzugefügt, da siehst Du es, refresh mal bitte. Thx

**Comment by rallep71** [comment]
Mqtt Abfrage geht ohne Probleme, dann in influx usw..., nur ich hätte halt gerne das es auch wieder in node red geht

**Comment by windkh** [comment]
Ich bau das gleich ein, werde eine neue version erstellen...

**Comment by rallep71** [comment]
Super!, wie gesagt, denn Typ Shelly hatte ich auch nicht auf dem Schirm, es gibt ihn, schaltet ein wenig mehr Leistung, aber viel liest man über diesen Typ nicht. Nur über blauen Plugs :D

**Comment by windkh** [comment]
@rallep71 10.2.0 bitte ausprobieren

**Comment by rallep71** [comment]
Wird sofort gemacht!

**Comment by windkh** [comment]
kannst die Datei 99-shelly.js auch bei dir lokal durch die neue im github ersetzen falls die palette noch nicht die neue Version anzeigt

**Comment by rallep71** [comment]
Geht, keine Fehler, melde mich wieder falls noch etwas sein sollte. Und! ich wollte mal Danke sagen für Deine toller Arbeit die Du hier machst!!! Verneig und Hut zieh! Thx

**Comment by windkh** [comment]
Danke, alles nur nebenbei als Hobby. Freut mich wenns jemand brauchen kann.

**Comment by rallep71** [comment]
Wirklich Super Karl Heinz! Ich wünschte manchmal mehr von Deiner Art! Node Red über die Updates zu bringen ist schon manchmal eine Kunst wie ich es die letzen zwei Jahre erfahren habe, machst jetzt das Update oder nicht? Geht danach deine Pumpem, - Lüftungs,- Reifeschranksteuerung oder nicht, geht der Türöffner, ja, nein, vielleicht? Ja, nicht ganz einfach manchmal...vielleicht sollte man irgendwann mal Stable, Dev usw einführen.
