### ISSUE TITLE
Node Red crashes after an Error

### ISSUE THREAD

**Issue by niwre2019** [windkh/node-red-contrib-shelly#98]
I keep having the problem that due to an error with the plugin Node Red crashes completely. Is there any way to catch this error so that this does not happen? I have attached the relevant part from the log. I am using the current version 10.5.0.

`Oct 28 15:43:20 homebridge Node-RED[13852]: 28 Oct 15:43:20 - [red] Uncaught Exception:
Oct 28 15:43:20 homebridge Node-RED[13852]: 28 Oct 15:43:20 - [error] Error: timeout of 5000ms exceeded
Oct 28 15:43:20 homebridge Node-RED[13852]:     at createError (/home/pi/.node-red/node_modules/node-red-contrib-shelly/node_modules/axios/lib/core/createError.js:16:15)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at RedirectableRequest.handleRequestTimeout (/home/pi/.node-red/node_modules/node-red-contrib-shelly/node_modules/axios/lib/adapters/http.js:369:16)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at RedirectableRequest.emit (node:events:513:28)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at RedirectableRequest.emit (node:domain:489:12)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at Timeout.<anonymous> (/home/pi/.node-red/node_modules/follow-redirects/index.js:164:12)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at listOnTimeout (node:internal/timers:559:17)
Oct 28 15:43:20 homebridge Node-RED[13852]:     at processTimers (node:internal/timers:502:7)
Oct 28 15:43:20 homebridge systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 15:43:20 homebridge systemd[1]: nodered.service: Failed with result 'exit-code'. `

**Comment by windkh** [comment]
Thanks for reporting.
When does that happen? Reproducable?
What shelly do you use?

**Comment by windkh** [comment]
Can you send me your flow?

**Comment by windkh** [comment]
I added some try catch statements in  the code. Please test 10.6.0

**Comment by niwre2019** [comment]
Thanks for the quick help, I will test the new version.

**Comment by windkh** [comment]
hm if that does not help. you could try to add a catch node to the flow...
I con only guess what could have been the problem from the information you provided.

**Comment by niwre2019** [comment]
Maybe the error is fixed with the update, otherwise I will still try that with the CATCH Node. As we all know, hope dies last.
